/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/consumerapp/consumerapp-add/consumerapp-add.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/consumerapp/consumerapp.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from 'md2/toast/toast';
import * as import11 from '../../../../app/shared/loader.service';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../../node_modules/@angular2-material/button/button.ngfactory';
import * as import15 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import16 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import18 from '../../../node_modules/@angular2-material/input/input.ngfactory';
import * as import19 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../../node_modules/md2/core/compatibility/style-compatibility.ngfactory';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from '@angular2-material/button/button';
import * as import24 from '@angular/forms/src/directives/validators';
import * as import25 from '@angular/forms/src/validators';
import * as import26 from '@angular2-material/input/input';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from 'md2/core/compatibility/style-compatibility';
import * as import32 from '@angular/forms/src/directives/ng_form';
import * as import33 from '@angular/forms/src/directives/control_container';
export class Wrapper_ConsumerappAddComponent {
  context:import0.ConsumerappAddComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.ConsumerappAddComponent(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ConsumerappAddComponent_Host:import2.RenderComponentType = (null as any);
class _View_ConsumerappAddComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ConsumerappAddComponent_0_4:Wrapper_ConsumerappAddComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumerappAddComponent_Host0,renderType_ConsumerappAddComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConsumerappAddComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConsumerappAddComponent_0_4 = new Wrapper_ConsumerappAddComponent(this.parentInjector.get(import8.ConsumerAppService),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.Md2Toast),this.parentInjector.get(import11.LoaderService));
    this._appEl_0.initComponent(this._ConsumerappAddComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ConsumerappAddComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConsumerappAddComponent) && (0 === requestNodeIndex))) { return this._ConsumerappAddComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConsumerappAddComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConsumerappAddComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ConsumerappAddComponent_Host === (null as any))) { (renderType_ConsumerappAddComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConsumerappAddComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConsumerappAddComponentNgFactory:import13.ComponentFactory<import0.ConsumerappAddComponent> = new import13.ComponentFactory<import0.ConsumerappAddComponent>('ng-component',viewFactory_ConsumerappAddComponent_Host0,import0.ConsumerappAddComponent);
const styles_ConsumerappAddComponent:any[] = ([] as any[]);
var renderType_ConsumerappAddComponent:import2.RenderComponentType = (null as any);
class _View_ConsumerappAddComponent0 extends import1.AppView<import0.ConsumerappAddComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _MdButton_12_4:import14.Wrapper_MdButton;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _NgForm_20_3:import15.Wrapper_NgForm;
  _ControlContainer_20_4:any;
  _NgControlStatusGroup_20_5:import16.Wrapper_NgControlStatusGroup;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _RequiredValidator_26_4:import17.Wrapper_RequiredValidator;
  _MaxLengthValidator_26_5:import17.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_26_6:any[];
  _MdInput_26_7:import18.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_26_8:any[];
  _NgModel_26_9:import19.Wrapper_NgModel;
  _NgControl_26_10:any;
  _NgControlStatus_26_11:import16.Wrapper_NgControlStatus;
  _StyleCompatibility_26_12:import20.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_26_0:import21.QueryList<any>;
  _query_MdHint_26_1:import21.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _RequiredValidator_37_4:import17.Wrapper_RequiredValidator;
  _MaxLengthValidator_37_5:import17.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_37_6:any[];
  _MdInput_37_7:import18.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_37_8:any[];
  _NgModel_37_9:import19.Wrapper_NgModel;
  _NgControl_37_10:any;
  _NgControlStatus_37_11:import16.Wrapper_NgControlStatus;
  _StyleCompatibility_37_12:import20.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_37_0:import21.QueryList<any>;
  _query_MdHint_37_1:import21.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import3.AppElement;
  _RequiredValidator_48_4:import17.Wrapper_RequiredValidator;
  _MaxLengthValidator_48_5:import17.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_48_6:any[];
  _MdInput_48_7:import18.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_48_8:any[];
  _NgModel_48_9:import19.Wrapper_NgModel;
  _NgControl_48_10:any;
  _NgControlStatus_48_11:import16.Wrapper_NgControlStatus;
  _StyleCompatibility_48_12:import20.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_48_0:import21.QueryList<any>;
  _query_MdHint_48_1:import21.QueryList<any>;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import3.AppElement;
  _MdButton_57_4:import14.Wrapper_MdButton;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumerappAddComponent0,renderType_ConsumerappAddComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','consumer-add');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title-block d-flex');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','title  items ');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Add New Consumer App',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','text-right items');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn-back btn-green');
    this.renderer.setElementAttribute(this._el_12,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_12,'type','submit');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import14.viewFactory_MdButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._MdButton_12_4 = new import14.Wrapper_MdButton(new import22.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._MdButton_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),' ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','material-icons');
    this._text_15 = this.renderer.createText(this._el_14,'arrow_back',(null as any));
    this._text_16 = this.renderer.createText((null as any),'Back',(null as any));
      compView_12.create(this._MdButton_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n\n\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_20_3 = new import15.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_20_4 = this._NgForm_20_3.context;
    this._NgControlStatusGroup_20_5 = new import16.Wrapper_NgControlStatusGroup(this._ControlContainer_20_4);
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-group');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','half-width');
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','full-width');
    this.renderer.setElementAttribute(this._el_26,'maxlength','255');
    this.renderer.setElementAttribute(this._el_26,'name','consumerName');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_26,'required','');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._appEl_26 = new import3.AppElement(26,24,this,this._el_26);
    var compView_26:any = import18.viewFactory_MdInput0(this.viewUtils,this.injector(26),this._appEl_26);
    this._RequiredValidator_26_4 = new import17.Wrapper_RequiredValidator();
    this._MaxLengthValidator_26_5 = new import17.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_26_6 = [
      this._RequiredValidator_26_4.context,
      this._MaxLengthValidator_26_5.context
    ]
    ;
    this._MdInput_26_7 = new import18.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_26_8 = [this._MdInput_26_7.context];
    this._NgModel_26_9 = new import19.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_26_6,(null as any),this._NG_VALUE_ACCESSOR_26_8);
    this._NgControl_26_10 = this._NgModel_26_9.context;
    this._NgControlStatus_26_11 = new import16.Wrapper_NgControlStatus(this._NgControl_26_10);
    this._StyleCompatibility_26_12 = new import20.Wrapper_StyleCompatibility(this.renderer,new import22.ElementRef(this._el_26));
    this._query_MdPlaceholder_26_0 = new import21.QueryList<any>();
    this._query_MdHint_26_1 = new import21.QueryList<any>();
    this._appEl_26.initComponent(this._MdInput_26_7.context,([] as any[]),compView_26);
    this._query_MdPlaceholder_26_0.reset(([] as any[]));
    this._MdInput_26_7.context._placeholderChild = this._query_MdPlaceholder_26_0.first;
    compView_26.create(this._MdInput_26_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','error');
    this._text_29 = this.renderer.createText(this._el_28,'Name is required',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','form-group');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','half-width');
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','full-width');
    this.renderer.setElementAttribute(this._el_37,'maxlength','1000');
    this.renderer.setElementAttribute(this._el_37,'name','consumerDescription');
    this.renderer.setElementAttribute(this._el_37,'placeholder','Description');
    this.renderer.setElementAttribute(this._el_37,'required','');
    this._appEl_37 = new import3.AppElement(37,35,this,this._el_37);
    var compView_37:any = import18.viewFactory_MdInput0(this.viewUtils,this.injector(37),this._appEl_37);
    this._RequiredValidator_37_4 = new import17.Wrapper_RequiredValidator();
    this._MaxLengthValidator_37_5 = new import17.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_37_6 = [
      this._RequiredValidator_37_4.context,
      this._MaxLengthValidator_37_5.context
    ]
    ;
    this._MdInput_37_7 = new import18.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_37_8 = [this._MdInput_37_7.context];
    this._NgModel_37_9 = new import19.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_37_6,(null as any),this._NG_VALUE_ACCESSOR_37_8);
    this._NgControl_37_10 = this._NgModel_37_9.context;
    this._NgControlStatus_37_11 = new import16.Wrapper_NgControlStatus(this._NgControl_37_10);
    this._StyleCompatibility_37_12 = new import20.Wrapper_StyleCompatibility(this.renderer,new import22.ElementRef(this._el_37));
    this._query_MdPlaceholder_37_0 = new import21.QueryList<any>();
    this._query_MdHint_37_1 = new import21.QueryList<any>();
    this._appEl_37.initComponent(this._MdInput_37_7.context,([] as any[]),compView_37);
    this._query_MdPlaceholder_37_0.reset(([] as any[]));
    this._MdInput_37_7.context._placeholderChild = this._query_MdPlaceholder_37_0.first;
    compView_37.create(this._MdInput_37_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','error');
    this._text_40 = this.renderer.createText(this._el_39,'Description is required',(null as any));
    this._text_41 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_43 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','form-group');
    this._text_45 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','half-width');
    this._text_47 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','full-width');
    this.renderer.setElementAttribute(this._el_48,'maxlength','255');
    this.renderer.setElementAttribute(this._el_48,'name','consumerCallBackUrl');
    this.renderer.setElementAttribute(this._el_48,'placeholder','Call Back Url');
    this.renderer.setElementAttribute(this._el_48,'required','');
    this.renderer.setElementAttribute(this._el_48,'type','text');
    this._appEl_48 = new import3.AppElement(48,46,this,this._el_48);
    var compView_48:any = import18.viewFactory_MdInput0(this.viewUtils,this.injector(48),this._appEl_48);
    this._RequiredValidator_48_4 = new import17.Wrapper_RequiredValidator();
    this._MaxLengthValidator_48_5 = new import17.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_48_6 = [
      this._RequiredValidator_48_4.context,
      this._MaxLengthValidator_48_5.context
    ]
    ;
    this._MdInput_48_7 = new import18.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_48_8 = [this._MdInput_48_7.context];
    this._NgModel_48_9 = new import19.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_48_6,(null as any),this._NG_VALUE_ACCESSOR_48_8);
    this._NgControl_48_10 = this._NgModel_48_9.context;
    this._NgControlStatus_48_11 = new import16.Wrapper_NgControlStatus(this._NgControl_48_10);
    this._StyleCompatibility_48_12 = new import20.Wrapper_StyleCompatibility(this.renderer,new import22.ElementRef(this._el_48));
    this._query_MdPlaceholder_48_0 = new import21.QueryList<any>();
    this._query_MdHint_48_1 = new import21.QueryList<any>();
    this._appEl_48.initComponent(this._MdInput_48_7.context,([] as any[]),compView_48);
    this._query_MdPlaceholder_48_0.reset(([] as any[]));
    this._MdInput_48_7.context._placeholderChild = this._query_MdPlaceholder_48_0.first;
    compView_48.create(this._MdInput_48_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_46,'div',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','error');
    this._text_51 = this.renderer.createText(this._el_50,'Call Back Url is required',(null as any));
    this._text_52 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_44,'\n\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','form-group');
    this.renderer.setElementAttribute(this._el_55,'id','group-btn');
    this._text_56 = this.renderer.createText(this._el_55,'\n            ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'button',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','btn-green');
    this.renderer.setElementAttribute(this._el_57,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_57,'type','submit');
    this._appEl_57 = new import3.AppElement(57,55,this,this._el_57);
    var compView_57:any = import14.viewFactory_MdButton0(this.viewUtils,this.injector(57),this._appEl_57);
    this._MdButton_57_4 = new import14.Wrapper_MdButton(new import22.ElementRef(this._el_57),this.renderer);
    this._appEl_57.initComponent(this._MdButton_57_4.context,([] as any[]),compView_57);
    this._text_58 = this.renderer.createText((null as any),'Submit',(null as any));
    compView_57.create(this._MdButton_57_4.context,[([] as any[]).concat([this._text_58])],(null as any));
    this._text_59 = this.renderer.createText(this._el_55,'\n            ',(null as any));
    this._text_60 = this.renderer.createText(this._el_55,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_3.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_20,'submit',this.eventHandler(this._handle_submit_20_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_20,'reset',this.eventHandler(this._handle_reset_20_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_1.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_26_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_1.bind(this)));
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_37_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_48,'ngModelChange',this.eventHandler(this._handle_ngModelChange_48_0.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_48,'click',this.eventHandler(this._handle_click_48_1.bind(this)));
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_48_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_48_0.bind(this)));
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    this._expr_71 = import7.UNINITIALIZED;
    this._expr_72 = import7.UNINITIALIZED;
    this._expr_73 = import7.UNINITIALIZED;
    this._expr_74 = import7.UNINITIALIZED;
    this._expr_79 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_57,'click',this.eventHandler(this._handle_click_57_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_57,'mousedown',this.eventHandler(this._handle_mousedown_57_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_57,'focus',this.eventHandler(this._handle_focus_57_2.bind(this)));
    var disposable_15:Function = this.renderer.listen(this._el_57,'blur',this.eventHandler(this._handle_blur_57_3.bind(this)));
    this._expr_80 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_12_4.context; }
    if (((token === import24.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4.context; }
    if (((token === import24.MaxLengthValidator) && (26 === requestNodeIndex))) { return this._MaxLengthValidator_26_5.context; }
    if (((token === import25.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_6; }
    if (((token === import26.MdInput) && (26 === requestNodeIndex))) { return this._MdInput_26_7.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_8; }
    if (((token === import28.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_9.context; }
    if (((token === import29.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_10; }
    if (((token === import30.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_11.context; }
    if (((token === import31.StyleCompatibility) && (26 === requestNodeIndex))) { return this._StyleCompatibility_26_12.context; }
    if (((token === import24.RequiredValidator) && (37 === requestNodeIndex))) { return this._RequiredValidator_37_4.context; }
    if (((token === import24.MaxLengthValidator) && (37 === requestNodeIndex))) { return this._MaxLengthValidator_37_5.context; }
    if (((token === import25.NG_VALIDATORS) && (37 === requestNodeIndex))) { return this._NG_VALIDATORS_37_6; }
    if (((token === import26.MdInput) && (37 === requestNodeIndex))) { return this._MdInput_37_7.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_8; }
    if (((token === import28.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_9.context; }
    if (((token === import29.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_10; }
    if (((token === import30.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_11.context; }
    if (((token === import31.StyleCompatibility) && (37 === requestNodeIndex))) { return this._StyleCompatibility_37_12.context; }
    if (((token === import24.RequiredValidator) && (48 === requestNodeIndex))) { return this._RequiredValidator_48_4.context; }
    if (((token === import24.MaxLengthValidator) && (48 === requestNodeIndex))) { return this._MaxLengthValidator_48_5.context; }
    if (((token === import25.NG_VALIDATORS) && (48 === requestNodeIndex))) { return this._NG_VALIDATORS_48_6; }
    if (((token === import26.MdInput) && (48 === requestNodeIndex))) { return this._MdInput_48_7.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (48 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_48_8; }
    if (((token === import28.NgModel) && (48 === requestNodeIndex))) { return this._NgModel_48_9.context; }
    if (((token === import29.NgControl) && (48 === requestNodeIndex))) { return this._NgControl_48_10; }
    if (((token === import30.NgControlStatus) && (48 === requestNodeIndex))) { return this._NgControlStatus_48_11.context; }
    if (((token === import31.StyleCompatibility) && (48 === requestNodeIndex))) { return this._StyleCompatibility_48_12.context; }
    if (((token === import23.MdButton) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._MdButton_57_4.context; }
    if (((token === import32.NgForm) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NgForm_20_3.context; }
    if (((token === import33.ControlContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._ControlContainer_20_4; }
    if (((token === import30.NgControlStatusGroup) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NgControlStatusGroup_20_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._NgForm_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._NgControlStatusGroup_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_15:any = '';
    this._RequiredValidator_26_4.check_required(currVal_15,throwOnChange,false);
    this._RequiredValidator_26_4.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_17:any = '255';
    this._MaxLengthValidator_26_5.check_maxlength(currVal_17,throwOnChange,false);
    this._MaxLengthValidator_26_5.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_19:any = '255';
    this._MdInput_26_7.check_maxlength(currVal_19,throwOnChange,false);
    const currVal_20:any = 'Name';
    this._MdInput_26_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = '';
    this._MdInput_26_7.check_required(currVal_21,throwOnChange,false);
    const currVal_22:any = 'text';
    this._MdInput_26_7.check_type(currVal_22,throwOnChange,false);
    const currVal_23:any = 'consumerName';
    this._MdInput_26_7.check_name(currVal_23,throwOnChange,false);
    this._MdInput_26_7.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_25:any = 'consumerName';
    this._NgModel_26_9.check_name(currVal_25,throwOnChange,false);
    const currVal_26:any = this.context.consumerModel.Name;
    this._NgModel_26_9.check_model(currVal_26,throwOnChange,false);
    this._NgModel_26_9.detectChangesInternal(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_11.detectChangesInternal(this,this._el_26,throwOnChange);
    this._StyleCompatibility_26_12.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_36:any = '';
    this._RequiredValidator_37_4.check_required(currVal_36,throwOnChange,false);
    this._RequiredValidator_37_4.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_38:any = '1000';
    this._MaxLengthValidator_37_5.check_maxlength(currVal_38,throwOnChange,false);
    this._MaxLengthValidator_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_40:any = '1000';
    this._MdInput_37_7.check_maxlength(currVal_40,throwOnChange,false);
    const currVal_41:any = 'Description';
    this._MdInput_37_7.check_placeholder(currVal_41,throwOnChange,false);
    const currVal_42:any = '';
    this._MdInput_37_7.check_required(currVal_42,throwOnChange,false);
    const currVal_43:any = 'consumerDescription';
    this._MdInput_37_7.check_name(currVal_43,throwOnChange,false);
    this._MdInput_37_7.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_45:any = 'consumerDescription';
    this._NgModel_37_9.check_name(currVal_45,throwOnChange,false);
    const currVal_46:any = this.context.consumerModel.Description;
    this._NgModel_37_9.check_model(currVal_46,throwOnChange,false);
    this._NgModel_37_9.detectChangesInternal(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_11.detectChangesInternal(this,this._el_37,throwOnChange);
    this._StyleCompatibility_37_12.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_56:any = '';
    this._RequiredValidator_48_4.check_required(currVal_56,throwOnChange,false);
    this._RequiredValidator_48_4.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_58:any = '255';
    this._MaxLengthValidator_48_5.check_maxlength(currVal_58,throwOnChange,false);
    this._MaxLengthValidator_48_5.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_60:any = '255';
    this._MdInput_48_7.check_maxlength(currVal_60,throwOnChange,false);
    const currVal_61:any = 'Call Back Url';
    this._MdInput_48_7.check_placeholder(currVal_61,throwOnChange,false);
    const currVal_62:any = '';
    this._MdInput_48_7.check_required(currVal_62,throwOnChange,false);
    const currVal_63:any = 'text';
    this._MdInput_48_7.check_type(currVal_63,throwOnChange,false);
    const currVal_64:any = 'consumerCallBackUrl';
    this._MdInput_48_7.check_name(currVal_64,throwOnChange,false);
    this._MdInput_48_7.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_66:any = 'consumerCallBackUrl';
    this._NgModel_48_9.check_name(currVal_66,throwOnChange,false);
    const currVal_67:any = this.context.consumerModel.CallbackUrl;
    this._NgModel_48_9.check_model(currVal_67,throwOnChange,false);
    this._NgModel_48_9.detectChangesInternal(this,this._el_48,throwOnChange);
    this._NgControlStatus_48_11.detectChangesInternal(this,this._el_48,throwOnChange);
    this._StyleCompatibility_48_12.detectChangesInternal(this,this._el_48,throwOnChange);
    if (this._MdButton_57_4.detectChangesInternal(this,this._el_57,throwOnChange)) { this._appEl_57.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_26_1.dirty) {
        this._query_MdHint_26_1.reset(([] as any[]));
        this._MdInput_26_7.context._hintChildren = this._query_MdHint_26_1;
        this._query_MdHint_26_1.notifyOnChanges();
      }
      if (this._query_MdHint_37_1.dirty) {
        this._query_MdHint_37_1.reset(([] as any[]));
        this._MdInput_37_7.context._hintChildren = this._query_MdHint_37_1;
        this._query_MdHint_37_1.notifyOnChanges();
      }
      if (this._query_MdHint_48_1.dirty) {
        this._query_MdHint_48_1.reset(([] as any[]));
        this._MdInput_48_7.context._hintChildren = this._query_MdHint_48_1;
        this._query_MdHint_48_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_26_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_37_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_48_7.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._MdButton_12_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_12,'md-button-focus',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatusGroup_20_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_20_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_20_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_20_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_20_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_20_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = (this._RequiredValidator_26_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_26,'required',((currVal_16 == (null as any))? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = (this._MaxLengthValidator_26_5.context.maxlength? this._MaxLengthValidator_26_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_26,'maxlength',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_24:any = this._MdInput_26_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_26,'align',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._NgControlStatus_26_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_26_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_26_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_26_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_26_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_26_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:boolean = !((this._NgModel_26_9.context.touched && !this._NgModel_26_9.context.valid) && this._NgModel_26_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementProperty(this._el_28,'hidden',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_37:any = (this._RequiredValidator_37_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementAttribute(this._el_37,'required',((currVal_37 == (null as any))? (null as any): currVal_37.toString()));
      this._expr_37 = currVal_37;
    }
    const currVal_39:any = (this._MaxLengthValidator_37_5.context.maxlength? this._MaxLengthValidator_37_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementAttribute(this._el_37,'maxlength',((currVal_39 == (null as any))? (null as any): currVal_39.toString()));
      this._expr_39 = currVal_39;
    }
    const currVal_44:any = this._MdInput_37_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementAttribute(this._el_37,'align',((currVal_44 == (null as any))? (null as any): currVal_44.toString()));
      this._expr_44 = currVal_44;
    }
    const currVal_47:any = this._NgControlStatus_37_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_37_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_37_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_37_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_37_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_37_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:boolean = !((this._NgModel_37_9.context.touched && !this._NgModel_37_9.context.valid) && this._NgModel_37_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementProperty(this._el_39,'hidden',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_57:any = (this._RequiredValidator_48_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementAttribute(this._el_48,'required',((currVal_57 == (null as any))? (null as any): currVal_57.toString()));
      this._expr_57 = currVal_57;
    }
    const currVal_59:any = (this._MaxLengthValidator_48_5.context.maxlength? this._MaxLengthValidator_48_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementAttribute(this._el_48,'maxlength',((currVal_59 == (null as any))? (null as any): currVal_59.toString()));
      this._expr_59 = currVal_59;
    }
    const currVal_65:any = this._MdInput_48_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementAttribute(this._el_48,'align',((currVal_65 == (null as any))? (null as any): currVal_65.toString()));
      this._expr_65 = currVal_65;
    }
    const currVal_68:any = this._NgControlStatus_48_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_48,'ng-untouched',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = this._NgControlStatus_48_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_48,'ng-touched',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = this._NgControlStatus_48_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_48,'ng-pristine',currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_71:any = this._NgControlStatus_48_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementClass(this._el_48,'ng-dirty',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_72:any = this._NgControlStatus_48_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementClass(this._el_48,'ng-valid',currVal_72);
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = this._NgControlStatus_48_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementClass(this._el_48,'ng-invalid',currVal_73);
      this._expr_73 = currVal_73;
    }
    const currVal_74:boolean = !((this._NgModel_48_9.context.touched && !this._NgModel_48_9.context.valid) && this._NgModel_48_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementProperty(this._el_50,'hidden',currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_79:boolean = !this._NgForm_20_3.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementProperty(this._el_57,'disabled',currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = this._MdButton_57_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementClass(this._el_57,'md-button-focus',currVal_80);
      this._expr_80 = currVal_80;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_26_9.context.ngOnDestroy();
    this._NgModel_37_9.context.ngOnDestroy();
    this._NgModel_48_9.context.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.cancel()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_1($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_2($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_3($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.Name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_1($event:any):boolean {
    this._appEl_26.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_26_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.Description = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_1($event:any):boolean {
    this._appEl_37.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_37_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.CallbackUrl = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_48_1($event:any):boolean {
    this._appEl_48.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_48_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_click_57_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.submitApps(this.context.consumerModel)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_57_1($event:any):boolean {
    this._appEl_57.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_57_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_57_2($event:any):boolean {
    this._appEl_57.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_57_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_57_3($event:any):boolean {
    this._appEl_57.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_57_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ConsumerappAddComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ConsumerappAddComponent> {
  if ((renderType_ConsumerappAddComponent === (null as any))) { (renderType_ConsumerappAddComponent = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_ConsumerappAddComponent,{})); }
  return new _View_ConsumerappAddComponent0(viewUtils,parentInjector,declarationEl);
}