/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/project/project-add/project-add.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from 'md2/toast/toast';
import * as import11 from '../../../../app/project/project.service';
import * as import12 from '../../../../app/shared/loader.service';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../../node_modules/@angular2-material/button/button.ngfactory';
import * as import16 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import18 from '../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import19 from '../../../node_modules/@angular2-material/input/input.ngfactory';
import * as import20 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import21 from '../../../node_modules/md2/core/compatibility/style-compatibility.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../../node_modules/@angular2-material/checkbox/checkbox.ngfactory';
import * as import24 from '../../../node_modules/md2/select/select.ngfactory';
import * as import25 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from '../../../node_modules/md2/multiselect/multiselect.ngfactory';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import30 from '@angular2-material/button/button';
import * as import31 from '@angular/forms/src/directives/validators';
import * as import32 from '@angular/forms/src/validators';
import * as import33 from '@angular2-material/input/input';
import * as import34 from '@angular/forms/src/directives/control_value_accessor';
import * as import35 from '@angular/forms/src/directives/ng_model';
import * as import36 from '@angular/forms/src/directives/ng_control';
import * as import37 from '@angular/forms/src/directives/ng_control_status';
import * as import38 from 'md2/core/compatibility/style-compatibility';
import * as import39 from '@angular2-material/checkbox/checkbox';
import * as import40 from '@angular/common/src/directives/ng_for';
import * as import41 from 'md2/select/select';
import * as import42 from 'md2/multiselect/multiselect';
import * as import43 from '@angular/forms/src/directives/ng_form';
import * as import44 from '@angular/forms/src/directives/control_container';
export class Wrapper_ProjectAddComponent {
  context:import0.ProjectAddComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.ProjectAddComponent(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_ProjectAddComponent_Host:import2.RenderComponentType = (null as any);
class _View_ProjectAddComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ProjectAddComponent_0_4:Wrapper_ProjectAddComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectAddComponent_Host0,renderType_ProjectAddComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProjectAddComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProjectAddComponent_0_4 = new Wrapper_ProjectAddComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.Md2Toast),this.parentInjector.get(import11.ProjectService),this.parentInjector.get(import12.LoaderService));
    this._appEl_0.initComponent(this._ProjectAddComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ProjectAddComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProjectAddComponent) && (0 === requestNodeIndex))) { return this._ProjectAddComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProjectAddComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProjectAddComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ProjectAddComponent_Host === (null as any))) { (renderType_ProjectAddComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ProjectAddComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProjectAddComponentNgFactory:import14.ComponentFactory<import0.ProjectAddComponent> = new import14.ComponentFactory<import0.ProjectAddComponent>('ng-component',viewFactory_ProjectAddComponent_Host0,import0.ProjectAddComponent);
const styles_ProjectAddComponent:any[] = ([] as any[]);
var renderType_ProjectAddComponent:import2.RenderComponentType = (null as any);
class _View_ProjectAddComponent0 extends import1.AppView<import0.ProjectAddComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _MdButton_12_4:import15.Wrapper_MdButton;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _NgForm_20_3:import16.Wrapper_NgForm;
  _ControlContainer_20_4:any;
  _NgControlStatusGroup_20_5:import17.Wrapper_NgControlStatusGroup;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _RequiredValidator_26_4:import18.Wrapper_RequiredValidator;
  _MaxLengthValidator_26_5:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_26_6:any[];
  _MdInput_26_7:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_26_8:any[];
  _NgModel_26_9:import20.Wrapper_NgModel;
  _NgControl_26_10:any;
  _NgControlStatus_26_11:import17.Wrapper_NgControlStatus;
  _StyleCompatibility_26_12:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_26_0:import22.QueryList<any>;
  _query_MdHint_26_1:import22.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _RequiredValidator_37_4:import18.Wrapper_RequiredValidator;
  _MaxLengthValidator_37_5:import18.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_37_6:any[];
  _MdInput_37_7:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_37_8:any[];
  _NgModel_37_9:import20.Wrapper_NgModel;
  _NgControl_37_10:any;
  _NgControlStatus_37_11:import17.Wrapper_NgControlStatus;
  _StyleCompatibility_37_12:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_37_0:import22.QueryList<any>;
  _query_MdHint_37_1:import22.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _MdCheckbox_50_4:import23.Wrapper_MdCheckbox;
  _NG_VALUE_ACCESSOR_50_5:any[];
  _NgModel_50_6:import20.Wrapper_NgModel;
  _NgControl_50_7:any;
  _NgControlStatus_50_8:import17.Wrapper_NgControlStatus;
  _StyleCompatibility_50_9:import21.Wrapper_StyleCompatibility;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import3.AppElement;
  _NgModel_57_4:import20.Wrapper_NgModel;
  _NgControl_57_5:any;
  _NgControlStatus_57_6:import17.Wrapper_NgControlStatus;
  _Md2Select_57_7:import24.Wrapper_Md2Select;
  _query_Md2Option_57_0:import22.QueryList<any>;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _appEl_59:import3.AppElement;
  _TemplateRef_59_5:any;
  _NgFor_59_6:import25.Wrapper_NgFor;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  /*private*/ _appEl_68:import3.AppElement;
  _Md2Multiselect_68_4:import26.Wrapper_Md2Multiselect;
  _NG_VALUE_ACCESSOR_68_5:any[];
  _NgModel_68_6:import20.Wrapper_NgModel;
  _NgControl_68_7:any;
  _NgControlStatus_68_8:import17.Wrapper_NgControlStatus;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  /*private*/ _appEl_73:import3.AppElement;
  _MdButton_73_4:import15.Wrapper_MdButton;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_82:any;
  /*private*/ _expr_85:any;
  /*private*/ _expr_86:any;
  /*private*/ _expr_87:any;
  /*private*/ _expr_88:any;
  /*private*/ _expr_89:any;
  /*private*/ _expr_90:any;
  /*private*/ _expr_99:any;
  /*private*/ _expr_100:any;
  /*private*/ _expr_101:any;
  /*private*/ _expr_102:any;
  /*private*/ _expr_105:any;
  /*private*/ _expr_106:any;
  /*private*/ _expr_107:any;
  /*private*/ _expr_108:any;
  /*private*/ _expr_109:any;
  /*private*/ _expr_110:any;
  /*private*/ _expr_115:any;
  /*private*/ _expr_116:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectAddComponent0,renderType_ProjectAddComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','project-add');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title-block d-flex');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','title items');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','in_block');
    this._text_7 = this.renderer.createText(this._el_6,'Add Project',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','text-right items');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn-back btn-green');
    this.renderer.setElementAttribute(this._el_12,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_12,'type','submit');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import15.viewFactory_MdButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._MdButton_12_4 = new import15.Wrapper_MdButton(new import27.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._MdButton_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),' ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','material-icons');
    this._text_15 = this.renderer.createText(this._el_14,'arrow_back',(null as any));
    this._text_16 = this.renderer.createText((null as any),'Back',(null as any));
      compView_12.create(this._MdButton_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_20_3 = new import16.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_20_4 = this._NgForm_20_3.context;
    this._NgControlStatusGroup_20_5 = new import17.Wrapper_NgControlStatusGroup(this._ControlContainer_20_4);
    this._text_21 = this.renderer.createText(this._el_20,'\n\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-group');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','half-width');
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','full-width');
    this.renderer.setElementAttribute(this._el_26,'maxlength','255');
    this.renderer.setElementAttribute(this._el_26,'name','name');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_26,'required','');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._appEl_26 = new import3.AppElement(26,24,this,this._el_26);
    var compView_26:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(26),this._appEl_26);
    this._RequiredValidator_26_4 = new import18.Wrapper_RequiredValidator();
    this._MaxLengthValidator_26_5 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_26_6 = [
      this._RequiredValidator_26_4.context,
      this._MaxLengthValidator_26_5.context
    ]
    ;
    this._MdInput_26_7 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_26_8 = [this._MdInput_26_7.context];
    this._NgModel_26_9 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_26_6,(null as any),this._NG_VALUE_ACCESSOR_26_8);
    this._NgControl_26_10 = this._NgModel_26_9.context;
    this._NgControlStatus_26_11 = new import17.Wrapper_NgControlStatus(this._NgControl_26_10);
    this._StyleCompatibility_26_12 = new import21.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_26));
    this._query_MdPlaceholder_26_0 = new import22.QueryList<any>();
    this._query_MdHint_26_1 = new import22.QueryList<any>();
    this._appEl_26.initComponent(this._MdInput_26_7.context,([] as any[]),compView_26);
    this._query_MdPlaceholder_26_0.reset(([] as any[]));
    this._MdInput_26_7.context._placeholderChild = this._query_MdPlaceholder_26_0.first;
    compView_26.create(this._MdInput_26_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','error');
    this._text_29 = this.renderer.createText(this._el_28,'Name is required',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_20,'\n\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','form-group');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','half-width');
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','full-width');
    this.renderer.setElementAttribute(this._el_37,'maxlength','255');
    this.renderer.setElementAttribute(this._el_37,'name','SlackChannelName');
    this.renderer.setElementAttribute(this._el_37,'placeholder','Slack Channel Name');
    this.renderer.setElementAttribute(this._el_37,'required','');
    this.renderer.setElementAttribute(this._el_37,'type','text');
    this._appEl_37 = new import3.AppElement(37,35,this,this._el_37);
    var compView_37:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(37),this._appEl_37);
    this._RequiredValidator_37_4 = new import18.Wrapper_RequiredValidator();
    this._MaxLengthValidator_37_5 = new import18.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_37_6 = [
      this._RequiredValidator_37_4.context,
      this._MaxLengthValidator_37_5.context
    ]
    ;
    this._MdInput_37_7 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_37_8 = [this._MdInput_37_7.context];
    this._NgModel_37_9 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_37_6,(null as any),this._NG_VALUE_ACCESSOR_37_8);
    this._NgControl_37_10 = this._NgModel_37_9.context;
    this._NgControlStatus_37_11 = new import17.Wrapper_NgControlStatus(this._NgControl_37_10);
    this._StyleCompatibility_37_12 = new import21.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_37));
    this._query_MdPlaceholder_37_0 = new import22.QueryList<any>();
    this._query_MdHint_37_1 = new import22.QueryList<any>();
    this._appEl_37.initComponent(this._MdInput_37_7.context,([] as any[]),compView_37);
    this._query_MdPlaceholder_37_0.reset(([] as any[]));
    this._MdInput_37_7.context._placeholderChild = this._query_MdPlaceholder_37_0.first;
    compView_37.create(this._MdInput_37_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','errors');
    this._el_40 = this.renderer.createElement(this._el_39,'div',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','error');
    this._text_41 = this.renderer.createText(this._el_40,'Slack Channel Name is required',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n\n            ',(null as any));
    this._text_43 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_44 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','form-group');
    this._text_46 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'label',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','lb-label');
    this._text_48 = this.renderer.createText(this._el_47,'Status',(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_45,'md-checkbox',(null as any));
    this.renderer.setElementAttribute(this._el_50,'id','chckbox');
    this.renderer.setElementAttribute(this._el_50,'name','IsActive');
    this.renderer.setElementAttribute(this._el_50,'type','checkbox');
    this._appEl_50 = new import3.AppElement(50,45,this,this._el_50);
    var compView_50:any = import23.viewFactory_MdCheckbox0(this.viewUtils,this.injector(50),this._appEl_50);
    this._MdCheckbox_50_4 = new import23.Wrapper_MdCheckbox(this.renderer,new import27.ElementRef(this._el_50));
    this._NG_VALUE_ACCESSOR_50_5 = [this._MdCheckbox_50_4.context];
    this._NgModel_50_6 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_50_5);
    this._NgControl_50_7 = this._NgModel_50_6.context;
    this._NgControlStatus_50_8 = new import17.Wrapper_NgControlStatus(this._NgControl_50_7);
    this._StyleCompatibility_50_9 = new import21.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_50));
    this._appEl_50.initComponent(this._MdCheckbox_50_4.context,([] as any[]),compView_50);
    compView_50.create(this._MdCheckbox_50_4.context,[([] as any[])],(null as any));
    this._text_51 = this.renderer.createText(this._el_45,'\n        ',(null as any));
    this._text_52 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','form-group');
    this._text_54 = this.renderer.createText(this._el_53,'\n            ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','half-width');
    this.renderer.setElementAttribute(this._el_55,'style','position:relative');
    this._text_56 = this.renderer.createText(this._el_55,'\n                ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'md2-select',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','field');
    this.renderer.setElementAttribute(this._el_57,'name','temleader');
    this.renderer.setElementAttribute(this._el_57,'placeholder','Teamleader');
    this.renderer.setElementAttribute(this._el_57,'role','select');
    this._appEl_57 = new import3.AppElement(57,55,this,this._el_57);
    var compView_57:any = import24.viewFactory_Md2Select0(this.viewUtils,this.injector(57),this._appEl_57);
    this._NgModel_57_4 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,(null as any),(null as any),(null as any));
    this._NgControl_57_5 = this._NgModel_57_4.context;
    this._NgControlStatus_57_6 = new import17.Wrapper_NgControlStatus(this._NgControl_57_5);
    this._Md2Select_57_7 = new import24.Wrapper_Md2Select(new import27.ElementRef(this._el_57),this._NgControl_57_5);
    this._query_Md2Option_57_0 = new import22.QueryList<any>();
    this._appEl_57.initComponent(this._Md2Select_57_7.context,([] as any[]),compView_57);
    this._text_58 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_59 = new import3.AppElement(59,57,this,this._anchor_59);
    this._TemplateRef_59_5 = new import28.TemplateRef_(this._appEl_59,viewFactory_ProjectAddComponent1);
    this._NgFor_59_6 = new import25.Wrapper_NgFor(this._appEl_59.vcRef,this._TemplateRef_59_5,this.parentInjector.get(import29.IterableDiffers),this.ref);
    this._text_60 = this.renderer.createText((null as any),'\n                ',(null as any));
      compView_57.create(this._Md2Select_57_7.context,[([] as any[]).concat([
        this._text_58,
        this._appEl_59,
        this._text_60
      ]
    )],(null as any));
    this._text_61 = this.renderer.createText(this._el_55,'\n            ',(null as any));
    this._text_62 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._text_63 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','form-group');
    this._text_65 = this.renderer.createText(this._el_64,'\n            ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_64,'div',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','half-width');
    this.renderer.setElementAttribute(this._el_66,'style','position:relative;');
    this._text_67 = this.renderer.createText(this._el_66,'\n                ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'md2-multiselect',(null as any));
    this.renderer.setElementAttribute(this._el_68,'item-text','UniqueName');
    this.renderer.setElementAttribute(this._el_68,'name','select');
    this.renderer.setElementAttribute(this._el_68,'placeholder','Select Team Members');
    this.renderer.setElementAttribute(this._el_68,'role','select');
    this._appEl_68 = new import3.AppElement(68,66,this,this._el_68);
    var compView_68:any = import26.viewFactory_Md2Multiselect0(this.viewUtils,this.injector(68),this._appEl_68);
    this._Md2Multiselect_68_4 = new import26.Wrapper_Md2Multiselect(new import27.ElementRef(this._el_68));
    this._NG_VALUE_ACCESSOR_68_5 = [this._Md2Multiselect_68_4.context];
    this._NgModel_68_6 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_68_5);
    this._NgControl_68_7 = this._NgModel_68_6.context;
    this._NgControlStatus_68_8 = new import17.Wrapper_NgControlStatus(this._NgControl_68_7);
    this._appEl_68.initComponent(this._Md2Multiselect_68_4.context,([] as any[]),compView_68);
    this._text_69 = this.renderer.createText((null as any),'\n                ',(null as any));
    compView_68.create(this._Md2Multiselect_68_4.context,([] as any[]),(null as any));
    this._text_70 = this.renderer.createText(this._el_66,'\n            ',(null as any));
    this._text_71 = this.renderer.createText(this._el_64,'\n        ',(null as any));
    this._text_72 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_20,'button',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','btn-green');
    this.renderer.setElementAttribute(this._el_73,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_73,'type','submit');
    this._appEl_73 = new import3.AppElement(73,20,this,this._el_73);
    var compView_73:any = import15.viewFactory_MdButton0(this.viewUtils,this.injector(73),this._appEl_73);
    this._MdButton_73_4 = new import15.Wrapper_MdButton(new import27.ElementRef(this._el_73),this.renderer);
    this._appEl_73.initComponent(this._MdButton_73_4.context,([] as any[]),compView_73);
    this._text_74 = this.renderer.createText((null as any),'Add New Project',(null as any));
    compView_73.create(this._MdButton_73_4.context,[([] as any[]).concat([this._text_74])],(null as any));
    this._text_75 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_77 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_3.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_20,'submit',this.eventHandler(this._handle_submit_20_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_20,'reset',this.eventHandler(this._handle_reset_20_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_1.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_26_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_1.bind(this)));
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_37_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_50,'ngModelChange',this.eventHandler(this._handle_ngModelChange_50_0.bind(this)));
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_50_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_50_0.bind(this)));
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    var disposable_11:Function = this.renderer.listen(this._el_57,'ngModelChange',this.eventHandler(this._handle_ngModelChange_57_0.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_57,'click',this.eventHandler(this._handle_click_57_1.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_57,'keydown',this.eventHandler(this._handle_keydown_57_2.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_57,'blur',this.eventHandler(this._handle_blur_57_3.bind(this)));
    const subscription_3:any = this._NgModel_57_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_57_0.bind(this)));
    this._expr_77 = import7.UNINITIALIZED;
    this._expr_78 = import7.UNINITIALIZED;
    this._expr_79 = import7.UNINITIALIZED;
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_81 = import7.UNINITIALIZED;
    this._expr_82 = import7.UNINITIALIZED;
    this._expr_85 = import7.UNINITIALIZED;
    this._expr_86 = import7.UNINITIALIZED;
    this._expr_87 = import7.UNINITIALIZED;
    this._expr_88 = import7.UNINITIALIZED;
    this._expr_89 = import7.UNINITIALIZED;
    this._expr_90 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_68,'ngModelChange',this.eventHandler(this._handle_ngModelChange_68_0.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_68,'click',this.eventHandler(this._handle_click_68_1.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_68,'keydown',this.eventHandler(this._handle_keydown_68_2.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_68,'blur',this.eventHandler(this._handle_blur_68_3.bind(this)));
    this._expr_99 = import7.UNINITIALIZED;
    this._expr_100 = import7.UNINITIALIZED;
    this._expr_101 = import7.UNINITIALIZED;
    this._expr_102 = import7.UNINITIALIZED;
    const subscription_4:any = this._NgModel_68_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_68_0.bind(this)));
    this._expr_105 = import7.UNINITIALIZED;
    this._expr_106 = import7.UNINITIALIZED;
    this._expr_107 = import7.UNINITIALIZED;
    this._expr_108 = import7.UNINITIALIZED;
    this._expr_109 = import7.UNINITIALIZED;
    this._expr_110 = import7.UNINITIALIZED;
    this._expr_115 = import7.UNINITIALIZED;
    var disposable_19:Function = this.renderer.listen(this._el_73,'click',this.eventHandler(this._handle_click_73_0.bind(this)));
    var disposable_20:Function = this.renderer.listen(this._el_73,'mousedown',this.eventHandler(this._handle_mousedown_73_1.bind(this)));
    var disposable_21:Function = this.renderer.listen(this._el_73,'focus',this.eventHandler(this._handle_focus_73_2.bind(this)));
    var disposable_22:Function = this.renderer.listen(this._el_73,'blur',this.eventHandler(this._handle_blur_73_3.bind(this)));
    this._expr_116 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18,
      disposable_19,
      disposable_20,
      disposable_21,
      disposable_22
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_12_4.context; }
    if (((token === import31.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4.context; }
    if (((token === import31.MaxLengthValidator) && (26 === requestNodeIndex))) { return this._MaxLengthValidator_26_5.context; }
    if (((token === import32.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_6; }
    if (((token === import33.MdInput) && (26 === requestNodeIndex))) { return this._MdInput_26_7.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_8; }
    if (((token === import35.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_9.context; }
    if (((token === import36.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_10; }
    if (((token === import37.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_11.context; }
    if (((token === import38.StyleCompatibility) && (26 === requestNodeIndex))) { return this._StyleCompatibility_26_12.context; }
    if (((token === import31.RequiredValidator) && (37 === requestNodeIndex))) { return this._RequiredValidator_37_4.context; }
    if (((token === import31.MaxLengthValidator) && (37 === requestNodeIndex))) { return this._MaxLengthValidator_37_5.context; }
    if (((token === import32.NG_VALIDATORS) && (37 === requestNodeIndex))) { return this._NG_VALIDATORS_37_6; }
    if (((token === import33.MdInput) && (37 === requestNodeIndex))) { return this._MdInput_37_7.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_8; }
    if (((token === import35.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_9.context; }
    if (((token === import36.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_10; }
    if (((token === import37.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_11.context; }
    if (((token === import38.StyleCompatibility) && (37 === requestNodeIndex))) { return this._StyleCompatibility_37_12.context; }
    if (((token === import39.MdCheckbox) && (50 === requestNodeIndex))) { return this._MdCheckbox_50_4.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (50 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_50_5; }
    if (((token === import35.NgModel) && (50 === requestNodeIndex))) { return this._NgModel_50_6.context; }
    if (((token === import36.NgControl) && (50 === requestNodeIndex))) { return this._NgControl_50_7; }
    if (((token === import37.NgControlStatus) && (50 === requestNodeIndex))) { return this._NgControlStatus_50_8.context; }
    if (((token === import38.StyleCompatibility) && (50 === requestNodeIndex))) { return this._StyleCompatibility_50_9.context; }
    if (((token === import28.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import40.NgFor) && (59 === requestNodeIndex))) { return this._NgFor_59_6.context; }
    if (((token === import35.NgModel) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgModel_57_4.context; }
    if (((token === import36.NgControl) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgControl_57_5; }
    if (((token === import37.NgControlStatus) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgControlStatus_57_6.context; }
    if (((token === import41.Md2Select) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Md2Select_57_7.context; }
    if (((token === import42.Md2Multiselect) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Md2Multiselect_68_4.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NG_VALUE_ACCESSOR_68_5; }
    if (((token === import35.NgModel) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgModel_68_6.context; }
    if (((token === import36.NgControl) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgControl_68_7; }
    if (((token === import37.NgControlStatus) && ((68 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._NgControlStatus_68_8.context; }
    if (((token === import30.MdButton) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._MdButton_73_4.context; }
    if (((token === import43.NgForm) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._NgForm_20_3.context; }
    if (((token === import44.ControlContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._ControlContainer_20_4; }
    if (((token === import37.NgControlStatusGroup) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 75)))) { return this._NgControlStatusGroup_20_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._NgForm_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._NgControlStatusGroup_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_15:any = '';
    this._RequiredValidator_26_4.check_required(currVal_15,throwOnChange,false);
    this._RequiredValidator_26_4.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_17:any = '255';
    this._MaxLengthValidator_26_5.check_maxlength(currVal_17,throwOnChange,false);
    this._MaxLengthValidator_26_5.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_19:any = '255';
    this._MdInput_26_7.check_maxlength(currVal_19,throwOnChange,false);
    const currVal_20:any = 'Name';
    this._MdInput_26_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = '';
    this._MdInput_26_7.check_required(currVal_21,throwOnChange,false);
    const currVal_22:any = 'text';
    this._MdInput_26_7.check_type(currVal_22,throwOnChange,false);
    const currVal_23:any = 'name';
    this._MdInput_26_7.check_name(currVal_23,throwOnChange,false);
    this._MdInput_26_7.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_25:any = 'name';
    this._NgModel_26_9.check_name(currVal_25,throwOnChange,false);
    const currVal_26:any = this.context.project.name;
    this._NgModel_26_9.check_model(currVal_26,throwOnChange,false);
    this._NgModel_26_9.detectChangesInternal(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_11.detectChangesInternal(this,this._el_26,throwOnChange);
    this._StyleCompatibility_26_12.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_36:any = '';
    this._RequiredValidator_37_4.check_required(currVal_36,throwOnChange,false);
    this._RequiredValidator_37_4.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_38:any = '255';
    this._MaxLengthValidator_37_5.check_maxlength(currVal_38,throwOnChange,false);
    this._MaxLengthValidator_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_40:any = '255';
    this._MdInput_37_7.check_maxlength(currVal_40,throwOnChange,false);
    const currVal_41:any = 'Slack Channel Name';
    this._MdInput_37_7.check_placeholder(currVal_41,throwOnChange,false);
    const currVal_42:any = '';
    this._MdInput_37_7.check_required(currVal_42,throwOnChange,false);
    const currVal_43:any = 'text';
    this._MdInput_37_7.check_type(currVal_43,throwOnChange,false);
    const currVal_44:any = 'SlackChannelName';
    this._MdInput_37_7.check_name(currVal_44,throwOnChange,false);
    this._MdInput_37_7.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_46:any = 'SlackChannelName';
    this._NgModel_37_9.check_name(currVal_46,throwOnChange,false);
    const currVal_47:any = this.context.project.slackChannelName;
    this._NgModel_37_9.check_model(currVal_47,throwOnChange,false);
    this._NgModel_37_9.detectChangesInternal(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_11.detectChangesInternal(this,this._el_37,throwOnChange);
    this._StyleCompatibility_37_12.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_56:any = 'chckbox';
    this._MdCheckbox_50_4.check_id(currVal_56,throwOnChange,false);
    const currVal_57:any = 'IsActive';
    this._MdCheckbox_50_4.check_name(currVal_57,throwOnChange,false);
    if (this._MdCheckbox_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    const currVal_63:any = 'IsActive';
    this._NgModel_50_6.check_name(currVal_63,throwOnChange,false);
    const currVal_64:any = this.context.project.isActive;
    this._NgModel_50_6.check_model(currVal_64,throwOnChange,false);
    this._NgModel_50_6.detectChangesInternal(this,this._el_50,throwOnChange);
    this._NgControlStatus_50_8.detectChangesInternal(this,this._el_50,throwOnChange);
    this._StyleCompatibility_50_9.detectChangesInternal(this,this._el_50,throwOnChange);
    const currVal_75:any = 'temleader';
    this._NgModel_57_4.check_name(currVal_75,throwOnChange,false);
    const currVal_76:any = this.context.project.teamLeaderId;
    this._NgModel_57_4.check_model(currVal_76,throwOnChange,false);
    this._NgModel_57_4.detectChangesInternal(this,this._el_57,throwOnChange);
    this._NgControlStatus_57_6.detectChangesInternal(this,this._el_57,throwOnChange);
    const currVal_83:any = 'temleader';
    this._Md2Select_57_7.check_name(currVal_83,throwOnChange,false);
    const currVal_84:any = 'Teamleader';
    this._Md2Select_57_7.check_placeholder(currVal_84,throwOnChange,false);
    this._Md2Select_57_7.detectChangesInternal(this,this._el_57,throwOnChange);
    const currVal_91:any = this.context.project.listUsers;
    this._NgFor_59_6.check_ngForOf(currVal_91,throwOnChange,false);
    this._NgFor_59_6.detectChangesInternal(this,this._anchor_59,throwOnChange);
    const currVal_96:any = 'Select Team Members';
    this._Md2Multiselect_68_4.check_placeholder(currVal_96,throwOnChange,false);
    const currVal_97:any = 'UniqueName';
    this._Md2Multiselect_68_4.check_textKey(currVal_97,throwOnChange,false);
    const currVal_98:any = this.context.project.listUsers;
    this._Md2Multiselect_68_4.check_options(currVal_98,throwOnChange,false);
    this._Md2Multiselect_68_4.detectChangesInternal(this,this._el_68,throwOnChange);
    const currVal_103:any = 'select';
    this._NgModel_68_6.check_name(currVal_103,throwOnChange,false);
    const currVal_104:any = this.context.project.applicationUsers;
    this._NgModel_68_6.check_model(currVal_104,throwOnChange,false);
    this._NgModel_68_6.detectChangesInternal(this,this._el_68,throwOnChange);
    this._NgControlStatus_68_8.detectChangesInternal(this,this._el_68,throwOnChange);
    if (this._MdButton_73_4.detectChangesInternal(this,this._el_73,throwOnChange)) { this._appEl_73.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_26_1.dirty) {
        this._query_MdHint_26_1.reset(([] as any[]));
        this._MdInput_26_7.context._hintChildren = this._query_MdHint_26_1;
        this._query_MdHint_26_1.notifyOnChanges();
      }
      if (this._query_MdHint_37_1.dirty) {
        this._query_MdHint_37_1.reset(([] as any[]));
        this._MdInput_37_7.context._hintChildren = this._query_MdHint_37_1;
        this._query_MdHint_37_1.notifyOnChanges();
      }
      if (this._query_Md2Option_57_0.dirty) {
          this._query_Md2Option_57_0.reset([this._appEl_59.mapNestedViews(_View_ProjectAddComponent1,(nestedView:_View_ProjectAddComponent1):any => {
            return [nestedView._Md2Option_0_4.context];
        })]);
        this._Md2Select_57_7.context.options = this._query_Md2Option_57_0;
        this._query_Md2Option_57_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_26_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_37_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Md2Select_57_7.context.ngAfterContentInit(); }
      this._Md2Select_57_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Md2Multiselect_68_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._MdButton_12_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_12,'md-button-focus',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatusGroup_20_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_20_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_20_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_20_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_20_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_20_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = (this._RequiredValidator_26_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_26,'required',((currVal_16 == (null as any))? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = (this._MaxLengthValidator_26_5.context.maxlength? this._MaxLengthValidator_26_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_26,'maxlength',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_24:any = this._MdInput_26_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_26,'align',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._NgControlStatus_26_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_26_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_26_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_26_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_26_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_26_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:boolean = !((this._NgModel_26_9.context.touched && !this._NgModel_26_9.context.valid) && this._NgModel_26_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementProperty(this._el_28,'hidden',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_37:any = (this._RequiredValidator_37_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementAttribute(this._el_37,'required',((currVal_37 == (null as any))? (null as any): currVal_37.toString()));
      this._expr_37 = currVal_37;
    }
    const currVal_39:any = (this._MaxLengthValidator_37_5.context.maxlength? this._MaxLengthValidator_37_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementAttribute(this._el_37,'maxlength',((currVal_39 == (null as any))? (null as any): currVal_39.toString()));
      this._expr_39 = currVal_39;
    }
    const currVal_45:any = this._MdInput_37_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementAttribute(this._el_37,'align',((currVal_45 == (null as any))? (null as any): currVal_45.toString()));
      this._expr_45 = currVal_45;
    }
    const currVal_48:any = this._NgControlStatus_37_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_37_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_37_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_37_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_37_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_37_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:boolean = !((this._NgModel_37_9.context.touched && !this._NgModel_37_9.context.valid) && this._NgModel_37_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementProperty(this._el_40,'hidden',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_58:any = this._MdCheckbox_50_4.context.indeterminate;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_50,'md-checkbox-indeterminate',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._MdCheckbox_50_4.context.checked;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_50,'md-checkbox-checked',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = this._MdCheckbox_50_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_50,'md-checkbox-disabled',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = (this._MdCheckbox_50_4.context.align == 'end');
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_50,'md-checkbox-align-end',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:any = this._MdCheckbox_50_4.context.hasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementClass(this._el_50,'md-checkbox-focused',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_65:any = this._NgControlStatus_50_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_50,'ng-untouched',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_50_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_50,'ng-touched',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_50_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_50,'ng-pristine',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_50_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_50,'ng-dirty',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = this._NgControlStatus_50_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_50,'ng-valid',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = this._NgControlStatus_50_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_50,'ng-invalid',currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_77:any = this._NgControlStatus_57_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setElementClass(this._el_57,'ng-untouched',currVal_77);
      this._expr_77 = currVal_77;
    }
    const currVal_78:any = this._NgControlStatus_57_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementClass(this._el_57,'ng-touched',currVal_78);
      this._expr_78 = currVal_78;
    }
    const currVal_79:any = this._NgControlStatus_57_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementClass(this._el_57,'ng-pristine',currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = this._NgControlStatus_57_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementClass(this._el_57,'ng-dirty',currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = this._NgControlStatus_57_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setElementClass(this._el_57,'ng-valid',currVal_81);
      this._expr_81 = currVal_81;
    }
    const currVal_82:any = this._NgControlStatus_57_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementClass(this._el_57,'ng-invalid',currVal_82);
      this._expr_82 = currVal_82;
    }
    const currVal_85:any = (this._Md2Select_57_7.context.disabled? (0 - 1): this._Md2Select_57_7.context.tabindex);
    if (import4.checkBinding(throwOnChange,this._expr_85,currVal_85)) {
      this.renderer.setElementProperty(this._el_57,'tabIndex',currVal_85);
      this._expr_85 = currVal_85;
    }
    const currVal_86:any = this._Md2Select_57_7.context.placeholder;
    if (import4.checkBinding(throwOnChange,this._expr_86,currVal_86)) {
      this.renderer.setElementAttribute(this._el_57,'aria-label',((currVal_86 == (null as any))? (null as any): currVal_86.toString()));
      this._expr_86 = currVal_86;
    }
    const currVal_87:any = this._Md2Select_57_7.context.required.toString();
    if (import4.checkBinding(throwOnChange,this._expr_87,currVal_87)) {
      this.renderer.setElementAttribute(this._el_57,'aria-required',((currVal_87 == (null as any))? (null as any): currVal_87.toString()));
      this._expr_87 = currVal_87;
    }
    const currVal_88:any = this._Md2Select_57_7.context.disabled.toString();
    if (import4.checkBinding(throwOnChange,this._expr_88,currVal_88)) {
      this.renderer.setElementAttribute(this._el_57,'aria-disabled',((currVal_88 == (null as any))? (null as any): currVal_88.toString()));
      this._expr_88 = currVal_88;
    }
    const currVal_89:any = (((this._Md2Select_57_7.context._control == (null as any))? (null as any): this._Md2Select_57_7.context._control.invalid) || 'false');
    if (import4.checkBinding(throwOnChange,this._expr_89,currVal_89)) {
      this.renderer.setElementAttribute(this._el_57,'aria-invalid',((currVal_89 == (null as any))? (null as any): currVal_89.toString()));
      this._expr_89 = currVal_89;
    }
    const currVal_90:any = this._Md2Select_57_7.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_90,currVal_90)) {
      this.renderer.setElementClass(this._el_57,'md2-select-disabled',currVal_90);
      this._expr_90 = currVal_90;
    }
    const currVal_99:any = this._Md2Multiselect_68_4.context.id;
    if (import4.checkBinding(throwOnChange,this._expr_99,currVal_99)) {
      this.renderer.setElementProperty(this._el_68,'id',currVal_99);
      this._expr_99 = currVal_99;
    }
    const currVal_100:any = this._Md2Multiselect_68_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_100,currVal_100)) {
      this.renderer.setElementClass(this._el_68,'md2-multiselect-disabled',currVal_100);
      this._expr_100 = currVal_100;
    }
    const currVal_101:any = (this._Md2Multiselect_68_4.context.disabled? (0 - 1): this._Md2Multiselect_68_4.context.tabindex);
    if (import4.checkBinding(throwOnChange,this._expr_101,currVal_101)) {
      this.renderer.setElementProperty(this._el_68,'tabIndex',currVal_101);
      this._expr_101 = currVal_101;
    }
    const currVal_102:any = this._Md2Multiselect_68_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_102,currVal_102)) {
      this.renderer.setElementAttribute(this._el_68,'aria-disabled',((currVal_102 == (null as any))? (null as any): currVal_102.toString()));
      this._expr_102 = currVal_102;
    }
    const currVal_105:any = this._NgControlStatus_68_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_105,currVal_105)) {
      this.renderer.setElementClass(this._el_68,'ng-untouched',currVal_105);
      this._expr_105 = currVal_105;
    }
    const currVal_106:any = this._NgControlStatus_68_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_106,currVal_106)) {
      this.renderer.setElementClass(this._el_68,'ng-touched',currVal_106);
      this._expr_106 = currVal_106;
    }
    const currVal_107:any = this._NgControlStatus_68_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_107,currVal_107)) {
      this.renderer.setElementClass(this._el_68,'ng-pristine',currVal_107);
      this._expr_107 = currVal_107;
    }
    const currVal_108:any = this._NgControlStatus_68_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_108,currVal_108)) {
      this.renderer.setElementClass(this._el_68,'ng-dirty',currVal_108);
      this._expr_108 = currVal_108;
    }
    const currVal_109:any = this._NgControlStatus_68_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_109,currVal_109)) {
      this.renderer.setElementClass(this._el_68,'ng-valid',currVal_109);
      this._expr_109 = currVal_109;
    }
    const currVal_110:any = this._NgControlStatus_68_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_110,currVal_110)) {
      this.renderer.setElementClass(this._el_68,'ng-invalid',currVal_110);
      this._expr_110 = currVal_110;
    }
    const currVal_115:boolean = !this._NgForm_20_3.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_115,currVal_115)) {
      this.renderer.setElementProperty(this._el_73,'disabled',currVal_115);
      this._expr_115 = currVal_115;
    }
    const currVal_116:any = this._MdButton_73_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_116,currVal_116)) {
      this.renderer.setElementClass(this._el_73,'md-button-focus',currVal_116);
      this._expr_116 = currVal_116;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_26_9.context.ngOnDestroy();
    this._NgModel_37_9.context.ngOnDestroy();
    this._NgModel_50_6.context.ngOnDestroy();
    this._NgModel_57_4.context.ngOnDestroy();
    this._NgModel_68_6.context.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.gotoProjects()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_1($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_2($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_3($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.project.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_1($event:any):boolean {
    this._appEl_26.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_26_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.project.slackChannelName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_1($event:any):boolean {
    this._appEl_37.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_37_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.project.isActive = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_57_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.project.teamLeaderId = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_57_1($event:any):boolean {
    this._appEl_57.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Select_57_7.context.onClick($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keydown_57_2($event:any):boolean {
    this._appEl_57.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Select_57_7.context._handleKeydown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_57_3($event:any):boolean {
    this._appEl_57.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Select_57_7.context._onBlur()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_68_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.project.applicationUsers = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_68_1($event:any):boolean {
    this._appEl_68.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Multiselect_68_4.context._handleClick($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keydown_68_2($event:any):boolean {
    this._appEl_68.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Multiselect_68_4.context._handleKeydown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_68_3($event:any):boolean {
    this._appEl_68.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Multiselect_68_4.context.onBlur()) !== false);
    return (true && pd_0);
  }
  private _handle_click_73_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addProject(this.context.project)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_73_1($event:any):boolean {
    this._appEl_73.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_73_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_73_2($event:any):boolean {
    this._appEl_73.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_73_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_73_3($event:any):boolean {
    this._appEl_73.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_73_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ProjectAddComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ProjectAddComponent> {
  if ((renderType_ProjectAddComponent === (null as any))) { (renderType_ProjectAddComponent = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ProjectAddComponent,{})); }
  return new _View_ProjectAddComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectAddComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Md2Option_0_4:import24.Wrapper_Md2Option;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectAddComponent1,renderType_ProjectAddComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'md2-option',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','option');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import24.viewFactory_Md2Option0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Md2Option_0_4 = new import24.Wrapper_Md2Option((<_View_ProjectAddComponent0>this.parent)._Md2Select_57_7.context,this.parent.parentInjector.get(import41.Md2SelectDispatcher),new import27.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._Md2Option_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    compView_0.create(this._Md2Option_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Md2Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Md2Option_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.$implicit.Id;
    this._Md2Option_0_4.check_value(currVal_1,throwOnChange,false);
    this._Md2Option_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Md2Option_0_4.context.focused;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'md2-option-focused',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Md2Option_0_4.context.id;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._Md2Option_0_4.context.selected;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'md2-option-selected',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._Md2Option_0_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'md2-option-disabled',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(2,'',this.context.$implicit.FirstName,'-',this.context.$implicit.Email,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_1,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { this._Md2Option_0_4.context.ngAfterViewChecked(); }
  }
  dirtyParentQueriesInternal():void {
    (<_View_ProjectAddComponent0>this.parent)._query_Md2Option_57_0.setDirty();
  }
  private _handle_click_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Option_0_4.context.onOptionClick($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ProjectAddComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectAddComponent1(viewUtils,parentInjector,declarationEl);
}