/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/users/user-list/user-list.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/users/user.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from 'md2/toast/toast';
import * as import11 from '../../../../app/shared/loader.service';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import15 from '../../../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import16 from '../../../node_modules/@angular2-material/button/button.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../../node_modules/md2/data-table/data-table.ngfactory';
import * as import19 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import20 from '@angular/common/src/pipes/date_pipe';
import * as import21 from '@angular/router/src/router_state';
import * as import22 from '@angular/common/src/location/location_strategy';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/core/src/linker/template_ref';
import * as import25 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import26 from '@angular/core/src/i18n/tokens';
import * as import27 from '@angular/router/src/directives/router_link';
import * as import28 from '@angular/router/src/directives/router_link_active';
import * as import29 from '@angular2-material/button/button';
import * as import30 from 'md2/data-table/data-table';
import * as import31 from '@angular/common/src/directives/ng_for';
import * as import32 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import33 from '@angular/common/src/directives/ng_if';
export class Wrapper_UserListComponent {
  context:import0.UserListComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.UserListComponent(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_UserListComponent_Host:import2.RenderComponentType = (null as any);
class _View_UserListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _UserListComponent_0_4:Wrapper_UserListComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserListComponent_Host0,renderType_UserListComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserListComponent_0_4 = new Wrapper_UserListComponent(this.parentInjector.get(import8.UserService),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.Md2Toast),this.parentInjector.get(import11.LoaderService));
    this._appEl_0.initComponent(this._UserListComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._UserListComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.UserListComponent) && (0 === requestNodeIndex))) { return this._UserListComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UserListComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserListComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_UserListComponent_Host === (null as any))) { (renderType_UserListComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_UserListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserListComponentNgFactory:import13.ComponentFactory<import0.UserListComponent> = new import13.ComponentFactory<import0.UserListComponent>('ng-component',viewFactory_UserListComponent_Host0,import0.UserListComponent);
const styles_UserListComponent:any[] = ([] as any[]);
var renderType_UserListComponent:import2.RenderComponentType = (null as any);
class _View_UserListComponent0 extends import1.AppView<import0.UserListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _RouterLink_12_4:import14.Wrapper_RouterLink;
  _RouterLinkActive_12_5:import15.Wrapper_RouterLinkActive;
  _MdButton_12_6:import16.Wrapper_MdButton;
  _query_RouterLink_12_0:import17.QueryList<any>;
  _query_RouterLinkWithHref_12_1:import17.QueryList<any>;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _Md2DataTable_19_3:import18.Wrapper_Md2DataTable;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Md2DataTableSortField_25_4:import18.Wrapper_Md2DataTableSortField;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Md2DataTableSortField_28_4:import18.Wrapper_Md2DataTableSortField;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _Md2DataTableSortField_31_4:import18.Wrapper_Md2DataTableSortField;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _Md2DataTableSortField_34_4:import18.Wrapper_Md2DataTableSortField;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Md2DataTableSortField_37_4:import18.Wrapper_Md2DataTableSortField;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _Md2DataTableSortField_40_4:import18.Wrapper_Md2DataTableSortField;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _Md2DataTableSortField_43_4:import18.Wrapper_Md2DataTableSortField;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Md2DataTableSortField_46_4:import18.Wrapper_Md2DataTableSortField;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import3.AppElement;
  _Md2DataTableSortField_49_4:import18.Wrapper_Md2DataTableSortField;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _anchor_56:any;
  /*private*/ _appEl_56:import3.AppElement;
  _TemplateRef_56_5:any;
  _NgFor_56_6:import19.Wrapper_NgFor;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import3.AppElement;
  _Md2Pagination_65_4:import18.Wrapper_Md2Pagination;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  /*private*/ _expr_6:any;
  _pipe_date_0:import20.DatePipe;
  _arr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserListComponent0,renderType_UserListComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'section',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','user-list');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title-block d-flex');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','title items');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','in_block');
    this._text_7 = this.renderer.createText(this._el_6,'Users',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','items text-right');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','add-link btn-green');
    this.renderer.setElementAttribute(this._el_12,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_12,'routerLink','/user/add');
    this.renderer.setElementAttribute(this._el_12,'routerLinkActive','active');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import16.viewFactory_MdButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._RouterLink_12_4 = new import14.Wrapper_RouterLink(this.parentInjector.get(import9.Router),this.parentInjector.get(import21.ActivatedRoute),this.parentInjector.get(import22.LocationStrategy));
    this._RouterLinkActive_12_5 = new import15.Wrapper_RouterLinkActive(this.parentInjector.get(import9.Router),new import23.ElementRef(this._el_12),this.renderer);
    this._MdButton_12_6 = new import16.Wrapper_MdButton(new import23.ElementRef(this._el_12),this.renderer);
    this._query_RouterLink_12_0 = new import17.QueryList<any>();
    this._query_RouterLinkWithHref_12_1 = new import17.QueryList<any>();
    this._appEl_12.initComponent(this._MdButton_12_6.context,([] as any[]),compView_12);
    this._el_13 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','material-icons');
    this._text_14 = this.renderer.createText(this._el_13,'add',(null as any));
    this._text_15 = this.renderer.createText((null as any),'Add User',(null as any));
      compView_12.create(this._MdButton_12_6.context,[([] as any[]).concat([
        this._el_13,
        this._text_15
      ]
    )],(null as any));
    this._text_16 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_0,'table',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','table-bordered table-user');
    this._Md2DataTable_19_3 = new import18.Wrapper_Md2DataTable();
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'thead',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'tr',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_25,'md2-sort-field','firstname');
    this._appEl_25 = new import3.AppElement(25,23,this,this._el_25);
    var compView_25:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Md2DataTableSortField_25_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_25.initComponent(this._Md2DataTableSortField_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'First Name',(null as any));
    compView_25.create(this._Md2DataTableSortField_25_4.context,[([] as any[]).concat([this._text_26])],(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_28,'md2-sort-field','lastname');
    this._appEl_28 = new import3.AppElement(28,23,this,this._el_28);
    var compView_28:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Md2DataTableSortField_28_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_28.initComponent(this._Md2DataTableSortField_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'Last Name',(null as any));
    compView_28.create(this._Md2DataTableSortField_28_4.context,[([] as any[]).concat([this._text_29])],(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_31,'md2-sort-field','email');
    this._appEl_31 = new import3.AppElement(31,23,this,this._el_31);
    var compView_31:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Md2DataTableSortField_31_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_31.initComponent(this._Md2DataTableSortField_31_4.context,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'Email',(null as any));
    compView_31.create(this._Md2DataTableSortField_31_4.context,[([] as any[]).concat([this._text_32])],(null as any));
    this._text_33 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_34,'md2-sort-field','status');
    this._appEl_34 = new import3.AppElement(34,23,this,this._el_34);
    var compView_34:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Md2DataTableSortField_34_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_34.initComponent(this._Md2DataTableSortField_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'Status',(null as any));
    compView_34.create(this._Md2DataTableSortField_34_4.context,[([] as any[]).concat([this._text_35])],(null as any));
    this._text_36 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_37,'md2-sort-field','slackusername');
    this._appEl_37 = new import3.AppElement(37,23,this,this._el_37);
    var compView_37:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Md2DataTableSortField_37_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_37.initComponent(this._Md2DataTableSortField_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'Slack User Name',(null as any));
    compView_37.create(this._Md2DataTableSortField_37_4.context,[([] as any[]).concat([this._text_38])],(null as any));
    this._text_39 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_40,'md2-sort-field','numberofcasualleave');
    this._appEl_40 = new import3.AppElement(40,23,this,this._el_40);
    var compView_40:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(40),this._appEl_40);
    this._Md2DataTableSortField_40_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_40.initComponent(this._Md2DataTableSortField_40_4.context,([] as any[]),compView_40);
    this._text_41 = this.renderer.createText((null as any),'Number Of Casual Leave',(null as any));
    compView_40.create(this._Md2DataTableSortField_40_4.context,[([] as any[]).concat([this._text_41])],(null as any));
    this._text_42 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_43,'md2-sort-field','numberofsickleave');
    this._appEl_43 = new import3.AppElement(43,23,this,this._el_43);
    var compView_43:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Md2DataTableSortField_43_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_43.initComponent(this._Md2DataTableSortField_43_4.context,([] as any[]),compView_43);
    this._text_44 = this.renderer.createText((null as any),'Number Of Sick Leave',(null as any));
    compView_43.create(this._Md2DataTableSortField_43_4.context,[([] as any[]).concat([this._text_44])],(null as any));
    this._text_45 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_46,'md2-sort-field','joiningdate');
    this._appEl_46 = new import3.AppElement(46,23,this,this._el_46);
    var compView_46:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Md2DataTableSortField_46_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_46.initComponent(this._Md2DataTableSortField_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'Joining Date',(null as any));
    compView_46.create(this._Md2DataTableSortField_46_4.context,[([] as any[]).concat([this._text_47])],(null as any));
    this._text_48 = this.renderer.createText(this._el_23,'\n                ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_23,'th',(null as any));
    this.renderer.setElementAttribute(this._el_49,'md2-sort-field','action');
    this._appEl_49 = new import3.AppElement(49,23,this,this._el_49);
    var compView_49:any = import18.viewFactory_Md2DataTableSortField0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Md2DataTableSortField_49_4 = new import18.Wrapper_Md2DataTableSortField(this._Md2DataTable_19_3.context);
    this._appEl_49.initComponent(this._Md2DataTableSortField_49_4.context,([] as any[]),compView_49);
    this._text_50 = this.renderer.createText((null as any),'Action',(null as any));
    compView_49.create(this._Md2DataTableSortField_49_4.context,[([] as any[]).concat([this._text_50])],(null as any));
    this._text_51 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_19,'tbody',(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._anchor_56 = this.renderer.createTemplateAnchor(this._el_54,(null as any));
    this._appEl_56 = new import3.AppElement(56,54,this,this._anchor_56);
    this._TemplateRef_56_5 = new import24.TemplateRef_(this._appEl_56,viewFactory_UserListComponent1);
    this._NgFor_56_6 = new import19.Wrapper_NgFor(this._appEl_56.vcRef,this._TemplateRef_56_5,this.parentInjector.get(import25.IterableDiffers),this.ref);
    this._text_57 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_19,'tfoot',(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n            ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'tr',(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n                ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'td',(null as any));
    this.renderer.setElementAttribute(this._el_63,'colspan','9');
    this._text_64 = this.renderer.createText(this._el_63,'\n                    ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_63,'md2-pagination',(null as any));
    this._appEl_65 = new import3.AppElement(65,63,this,this._el_65);
    var compView_65:any = import18.viewFactory_Md2Pagination0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Md2Pagination_65_4 = new import18.Wrapper_Md2Pagination(this._Md2DataTable_19_3.context);
    this._appEl_65.initComponent(this._Md2Pagination_65_4.context,([] as any[]),compView_65);
    compView_65.create(this._Md2Pagination_65_4.context,([] as any[]),(null as any));
    this._text_66 = this.renderer.createText(this._el_63,'\n                ',(null as any));
    this._text_67 = this.renderer.createText(this._el_61,'\n            ',(null as any));
    this._text_68 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_70 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_3.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._pipe_date_0 = new import20.DatePipe(this.parentInjector.get(import26.LOCALE_ID));
    this._arr_0 = import4.pureProxy3((p0:any,p1:any,p2:any):any[] => {
      return [
        p0,
        p1,
        p2
      ]
      ;
    });
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._anchor_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.RouterLink) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLink_12_4.context; }
    if (((token === import28.RouterLinkActive) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkActive_12_5.context; }
    if (((token === import29.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdButton_12_6.context; }
    if (((token === import30.Md2DataTableSortField) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Md2DataTableSortField_25_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Md2DataTableSortField_28_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Md2DataTableSortField_31_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Md2DataTableSortField_34_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._Md2DataTableSortField_37_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Md2DataTableSortField_40_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Md2DataTableSortField_43_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Md2DataTableSortField_46_4.context; }
    if (((token === import30.Md2DataTableSortField) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Md2DataTableSortField_49_4.context; }
    if (((token === import24.TemplateRef) && (56 === requestNodeIndex))) { return this._TemplateRef_56_5; }
    if (((token === import31.NgFor) && (56 === requestNodeIndex))) { return this._NgFor_56_6.context; }
    if (((token === import30.Md2Pagination) && (65 === requestNodeIndex))) { return this._Md2Pagination_65_4.context; }
    if (((token === import30.Md2DataTable) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Md2DataTable_19_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = '/user/add';
    this._RouterLink_12_4.check_routerLink(currVal_4,throwOnChange,false);
    this._RouterLink_12_4.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_5:any = 'active';
    this._RouterLinkActive_12_5.check_routerLinkActive(currVal_5,throwOnChange,false);
    this._RouterLinkActive_12_5.detectChangesInternal(this,this._el_12,throwOnChange);
    if (this._MdButton_12_6.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    const currVal_7:any = this.context.users;
    this._Md2DataTable_19_3.check_inputData(currVal_7,throwOnChange,false);
    const currVal_8:any = 10;
    this._Md2DataTable_19_3.check_pageLength(currVal_8,throwOnChange,false);
    this._Md2DataTable_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_9:any = 'firstname';
    this._Md2DataTableSortField_25_4.check_sortField(currVal_9,throwOnChange,false);
    this._Md2DataTableSortField_25_4.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_10:any = 'lastname';
    this._Md2DataTableSortField_28_4.check_sortField(currVal_10,throwOnChange,false);
    this._Md2DataTableSortField_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_11:any = 'email';
    this._Md2DataTableSortField_31_4.check_sortField(currVal_11,throwOnChange,false);
    this._Md2DataTableSortField_31_4.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_12:any = 'status';
    this._Md2DataTableSortField_34_4.check_sortField(currVal_12,throwOnChange,false);
    this._Md2DataTableSortField_34_4.detectChangesInternal(this,this._el_34,throwOnChange);
    const currVal_13:any = 'slackusername';
    this._Md2DataTableSortField_37_4.check_sortField(currVal_13,throwOnChange,false);
    this._Md2DataTableSortField_37_4.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_14:any = 'numberofcasualleave';
    this._Md2DataTableSortField_40_4.check_sortField(currVal_14,throwOnChange,false);
    this._Md2DataTableSortField_40_4.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_15:any = 'numberofsickleave';
    this._Md2DataTableSortField_43_4.check_sortField(currVal_15,throwOnChange,false);
    this._Md2DataTableSortField_43_4.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_16:any = 'joiningdate';
    this._Md2DataTableSortField_46_4.check_sortField(currVal_16,throwOnChange,false);
    this._Md2DataTableSortField_46_4.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_17:any = 'action';
    this._Md2DataTableSortField_49_4.check_sortField(currVal_17,throwOnChange,false);
    this._Md2DataTableSortField_49_4.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_18:any = this._Md2DataTable_19_3.context.data;
    this._NgFor_56_6.check_ngForOf(currVal_18,throwOnChange,false);
    this._NgFor_56_6.detectChangesInternal(this,this._anchor_56,throwOnChange);
    const currVal_19:any = this._arr_0(5,10,15);
    this._Md2Pagination_65_4.check_rows(currVal_19,throwOnChange,false);
    this._Md2Pagination_65_4.detectChangesInternal(this,this._el_65,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_12_0.dirty) {
        this._query_RouterLink_12_0.reset([this._RouterLink_12_4.context]);
        this._RouterLinkActive_12_5.context.links = this._query_RouterLink_12_0;
        this._query_RouterLink_12_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_12_1.dirty) {
        this._query_RouterLinkWithHref_12_1.reset(([] as any[]));
        this._RouterLinkActive_12_5.context.linksWithHrefs = this._query_RouterLinkWithHref_12_1;
        this._query_RouterLinkWithHref_12_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_12_5.context.ngAfterContentInit(); }
    }
    const currVal_6:any = this._MdButton_12_6.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_12,'md-button-focus',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Md2Pagination_65_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._RouterLinkActive_12_5.context.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLink_12_4.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_1($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_6.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_2($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_6.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_3($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_6.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserListComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.UserListComponent> {
  if ((renderType_UserListComponent === (null as any))) { (renderType_UserListComponent = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_UserListComponent,{})); }
  return new _View_UserListComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserListComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import3.AppElement;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import32.Wrapper_NgIf;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import32.Wrapper_NgIf;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _MdButton_29_4:import16.Wrapper_MdButton;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _MdButton_32_4:import16.Wrapper_MdButton;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _MdButton_35_4:import16.Wrapper_MdButton;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  _pipe_date_0_0:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserListComponent1,renderType_UserListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_11 = new import3.AppElement(11,0,this,this._anchor_11);
    this._TemplateRef_11_5 = new import24.TemplateRef_(this._appEl_11,viewFactory_UserListComponent2);
    this._NgIf_11_6 = new import32.Wrapper_NgIf(this._appEl_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_13 = new import3.AppElement(13,0,this,this._anchor_13);
    this._TemplateRef_13_5 = new import24.TemplateRef_(this._appEl_13,viewFactory_UserListComponent3);
    this._NgIf_13_6 = new import32.Wrapper_NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','btn-green custom-btn mr-5');
    this.renderer.setElementAttribute(this._el_29,'md-raised-button','');
    this._appEl_29 = new import3.AppElement(29,27,this,this._el_29);
    var compView_29:any = import16.viewFactory_MdButton0(this.viewUtils,this.injector(29),this._appEl_29);
    this._MdButton_29_4 = new import16.Wrapper_MdButton(new import23.ElementRef(this._el_29),this.renderer);
    this._appEl_29.initComponent(this._MdButton_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'Details',(null as any));
    compView_29.create(this._MdButton_29_4.context,[([] as any[]).concat([this._text_30])],(null as any));
    this._text_31 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_27,'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','custom-btn');
    this.renderer.setElementAttribute(this._el_32,'md-raised-button','');
    this._appEl_32 = new import3.AppElement(32,27,this,this._el_32);
    var compView_32:any = import16.viewFactory_MdButton0(this.viewUtils,this.injector(32),this._appEl_32);
    this._MdButton_32_4 = new import16.Wrapper_MdButton(new import23.ElementRef(this._el_32),this.renderer);
    this._appEl_32.initComponent(this._MdButton_32_4.context,([] as any[]),compView_32);
    this._text_33 = this.renderer.createText((null as any),'Edit',(null as any));
    compView_32.create(this._MdButton_32_4.context,[([] as any[]).concat([this._text_33])],(null as any));
    this._text_34 = this.renderer.createText(this._el_27,'\n                    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_27,'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','btn-green custom-btn mr-5');
    this.renderer.setElementAttribute(this._el_35,'md-raised-button','');
    this._appEl_35 = new import3.AppElement(35,27,this,this._el_35);
    var compView_35:any = import16.viewFactory_MdButton0(this.viewUtils,this.injector(35),this._appEl_35);
    this._MdButton_35_4 = new import16.Wrapper_MdButton(new import23.ElementRef(this._el_35),this.renderer);
    this._appEl_35.initComponent(this._MdButton_35_4.context,([] as any[]),compView_35);
    this._text_36 = this.renderer.createText((null as any),'ReSendMail',(null as any));
    compView_35.create(this._MdButton_35_4.context,[([] as any[]).concat([this._text_36])],(null as any));
    this._text_37 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._pipe_date_0_0 = import4.pureProxy2((<_View_UserListComponent0>this.parent)._pipe_date_0.transform.bind((<_View_UserListComponent0>this.parent)._pipe_date_0));
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_29,'mousedown',this.eventHandler(this._handle_mousedown_29_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_29,'focus',this.eventHandler(this._handle_focus_29_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_29,'blur',this.eventHandler(this._handle_blur_29_3.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_32,'mousedown',this.eventHandler(this._handle_mousedown_32_1.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_32,'focus',this.eventHandler(this._handle_focus_32_2.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_32,'blur',this.eventHandler(this._handle_blur_32_3.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_35,'mousedown',this.eventHandler(this._handle_mousedown_35_1.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_35,'focus',this.eventHandler(this._handle_focus_35_2.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_35,'blur',this.eventHandler(this._handle_blur_35_3.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import33.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import24.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import33.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6.context; }
    if (((token === import29.MdButton) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._MdButton_29_4.context; }
    if (((token === import29.MdButton) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._MdButton_32_4.context; }
    if (((token === import29.MdButton) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._MdButton_35_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_3:any = this.context.$implicit.IsActive;
    this._NgIf_11_6.check_ngIf(currVal_3,throwOnChange,false);
    this._NgIf_11_6.detectChangesInternal(this,this._anchor_11,throwOnChange);
    const currVal_4:boolean = !this.context.$implicit.IsActive;
    this._NgIf_13_6.check_ngIf(currVal_4,throwOnChange,false);
    this._NgIf_13_6.detectChangesInternal(this,this._anchor_13,throwOnChange);
    if (this._MdButton_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    if (this._MdButton_32_4.detectChangesInternal(this,this._el_32,throwOnChange)) { this._appEl_32.componentView.markAsCheckOnce(); }
    if (this._MdButton_35_4.detectChangesInternal(this,this._el_35,throwOnChange)) { this._appEl_35.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.FirstName,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.LastName,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.Email,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_9,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.SlackUserName,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_16,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.$implicit.NumberOfCasualLeave,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_19,currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.$implicit.NumberOfSickLeave,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_22,currVal_7);
      this._expr_7 = currVal_7;
    }
    valUnwrapper.reset();
    const currVal_8:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,(<_View_UserListComponent0>this.parent)._pipe_date_0.transform)(this.context.$implicit.JoiningDate,'dd/MM/yyyy')),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_8,currVal_8))) {
      this.renderer.setText(this._text_25,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = this._MdButton_29_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_29,'md-button-focus',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_18:any = this._MdButton_32_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_32,'md-button-focus',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_23:any = this._MdButton_35_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_35,'md-button-focus',currVal_23);
      this._expr_23 = currVal_23;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.userDetails(this.context.$implicit.Id)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_29_1($event:any):boolean {
    this._appEl_29.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_29_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_29_2($event:any):boolean {
    this._appEl_29.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_29_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_29_3($event:any):boolean {
    this._appEl_29.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_29_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.userEdit(this.context.$implicit.Id)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_32_1($event:any):boolean {
    this._appEl_32.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_32_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_32_2($event:any):boolean {
    this._appEl_32.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_32_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_32_3($event:any):boolean {
    this._appEl_32.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_32_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.reSendMail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_35_1($event:any):boolean {
    this._appEl_35.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_35_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_35_2($event:any):boolean {
    this._appEl_35.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_35_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_35_3($event:any):boolean {
    this._appEl_35.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_35_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserListComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserListComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_UserListComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserListComponent2,renderType_UserListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Active',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_UserListComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserListComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_UserListComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserListComponent3,renderType_UserListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'td',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Inactive',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_UserListComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserListComponent3(viewUtils,parentInjector,declarationEl);
}