/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/users/user.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../../app/login.service';
import * as import5 from '../../../app/users/user.service';
import * as import6 from '@angular/core/src/linker/view_utils';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '../../../app/http.service';
import * as import11 from '@angular/router/src/router';
import * as import12 from '../../../app/shared/userrole.model';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import16 from '@angular/router/src/router_outlet_map';
import * as import17 from '@angular/core/src/linker/component_factory_resolver';
import * as import18 from '@angular/router/src/directives/router_outlet';
export class Wrapper_UserComponent {
  context:import0.UserComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.UserComponent(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_UserComponent_Host:import2.RenderComponentType = (null as any);
class _View_UserComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginService_0_4:import4.LoginService;
  _UserComponent_0_5:Wrapper_UserComponent;
  __UserService_0_6:import5.UserService;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_UserComponent_Host0,renderType_UserComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  get _UserService_0_6():import5.UserService {
    if ((this.__UserService_0_6 == (null as any))) { (this.__UserService_0_6 = new import5.UserService(this.parentInjector.get(import10.HttpService),this.parentInjector.get(import10.HttpService))); }
    return this.__UserService_0_6;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginService_0_4 = new import4.LoginService(this.parentInjector.get(import10.HttpService));
    this._UserComponent_0_5 = new Wrapper_UserComponent(this._LoginService_0_4,this.parentInjector.get(import11.Router),this.parentInjector.get(import12.UserRole));
    this._appEl_0.initComponent(this._UserComponent_0_5.context,([] as any[]),compView_0);
    compView_0.create(this._UserComponent_0_5.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.LoginService) && (0 === requestNodeIndex))) { return this._LoginService_0_4; }
    if (((token === import0.UserComponent) && (0 === requestNodeIndex))) { return this._UserComponent_0_5.context; }
    if (((token === import5.UserService) && (0 === requestNodeIndex))) { return this._UserService_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UserComponent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserComponent_Host0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_UserComponent_Host === (null as any))) { (renderType_UserComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_UserComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserComponentNgFactory:import14.ComponentFactory<import0.UserComponent> = new import14.ComponentFactory<import0.UserComponent>('ng-component',viewFactory_UserComponent_Host0,import0.UserComponent);
const styles_UserComponent:any[] = ([] as any[]);
var renderType_UserComponent:import2.RenderComponentType = (null as any);
class _View_UserComponent0 extends import1.AppView<import0.UserComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _RouterOutlet_1_5:import15.Wrapper_RouterOutlet;
  constructor(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement) {
    super(_View_UserComponent0,renderType_UserComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    this._RouterOutlet_1_5 = new import15.Wrapper_RouterOutlet(this.parentInjector.get(import16.RouterOutletMap),this._appEl_1.vcRef,this.parentInjector.get(import17.ComponentFactoryResolver),(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.RouterOutlet) && (1 === requestNodeIndex))) { return this._RouterOutlet_1_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RouterOutlet_1_5.detectChangesInternal(this,this._el_1,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_1_5.context.ngOnDestroy();
  }
}
export function viewFactory_UserComponent0(viewUtils:import6.ViewUtils,parentInjector:import7.Injector,declarationEl:import3.AppElement):import1.AppView<import0.UserComponent> {
  if ((renderType_UserComponent === (null as any))) { (renderType_UserComponent = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_UserComponent,{})); }
  return new _View_UserComponent0(viewUtils,parentInjector,declarationEl);
}