/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/change-password/changepassword.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../../app/users/user.service';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../app/http.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from '@angular/router/src/router_outlet_map';
import * as import14 from '@angular/core/src/linker/component_factory_resolver';
import * as import15 from '@angular/router/src/directives/router_outlet';
export class Wrapper_ChangePasswordMainComponent {
  context:import0.ChangePasswordMainComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ChangePasswordMainComponent();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ChangePasswordMainComponent_Host:import2.RenderComponentType = (null as any);
class _View_ChangePasswordMainComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ChangePasswordMainComponent_0_4:Wrapper_ChangePasswordMainComponent;
  __UserService_0_5:import4.UserService;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_ChangePasswordMainComponent_Host0,renderType_ChangePasswordMainComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  get _UserService_0_5():import4.UserService {
    if ((this.__UserService_0_5 == (null as any))) { (this.__UserService_0_5 = new import4.UserService(this.parentInjector.get(import9.HttpService),this.parentInjector.get(import9.HttpService))); }
    return this.__UserService_0_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ChangePasswordMainComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ChangePasswordMainComponent_0_4 = new Wrapper_ChangePasswordMainComponent();
    this._appEl_0.initComponent(this._ChangePasswordMainComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ChangePasswordMainComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ChangePasswordMainComponent) && (0 === requestNodeIndex))) { return this._ChangePasswordMainComponent_0_4.context; }
    if (((token === import4.UserService) && (0 === requestNodeIndex))) { return this._UserService_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ChangePasswordMainComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ChangePasswordMainComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ChangePasswordMainComponent_Host === (null as any))) { (renderType_ChangePasswordMainComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ChangePasswordMainComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ChangePasswordMainComponentNgFactory:import11.ComponentFactory<import0.ChangePasswordMainComponent> = new import11.ComponentFactory<import0.ChangePasswordMainComponent>('ng-component',viewFactory_ChangePasswordMainComponent_Host0,import0.ChangePasswordMainComponent);
const styles_ChangePasswordMainComponent:any[] = ([] as any[]);
var renderType_ChangePasswordMainComponent:import2.RenderComponentType = (null as any);
class _View_ChangePasswordMainComponent0 extends import1.AppView<import0.ChangePasswordMainComponent> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _RouterOutlet_1_5:import12.Wrapper_RouterOutlet;
  _text_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_ChangePasswordMainComponent0,renderType_ChangePasswordMainComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    this._RouterOutlet_1_5 = new import12.Wrapper_RouterOutlet(this.parentInjector.get(import13.RouterOutletMap),this._appEl_1.vcRef,this.parentInjector.get(import14.ComponentFactoryResolver),(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.RouterOutlet) && (1 === requestNodeIndex))) { return this._RouterOutlet_1_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RouterOutlet_1_5.detectChangesInternal(this,this._el_1,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_1_5.context.ngOnDestroy();
  }
}
export function viewFactory_ChangePasswordMainComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ChangePasswordMainComponent> {
  if ((renderType_ChangePasswordMainComponent === (null as any))) { (renderType_ChangePasswordMainComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_ChangePasswordMainComponent,{})); }
  return new _View_ChangePasswordMainComponent0(viewUtils,parentInjector,declarationEl);
}