/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/consumerapp/consumerapp-edit/consumer-edit.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../../../app/consumerapp/consumerapp.service';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from 'md2/toast/toast';
import * as import12 from '@angular/common/src/location/location';
import * as import13 from '../../../../app/shared/loader.service';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '../../../node_modules/@angular2-material/button/button.ngfactory';
import * as import17 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import18 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import19 from '../../../node_modules/@angular2-material/input/input.ngfactory';
import * as import20 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import21 from '../../../node_modules/md2/core/compatibility/style-compatibility.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular2-material/button/button';
import * as import26 from '@angular2-material/input/input';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from 'md2/core/compatibility/style-compatibility';
import * as import32 from '@angular/forms/src/directives/validators';
import * as import33 from '@angular/forms/src/validators';
import * as import34 from '@angular/forms/src/directives/ng_form';
import * as import35 from '@angular/forms/src/directives/control_container';
export class Wrapper_ConsumerappEditComponent {
  context:import0.ConsumerappEditComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any) {
    this.changed = false;
    this.context = new import0.ConsumerappEditComponent(p0,p1,p2,p3,p4,p5);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_ConsumerappEditComponent_Host:import2.RenderComponentType = (null as any);
class _View_ConsumerappEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ConsumerappEditComponent_0_4:Wrapper_ConsumerappEditComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumerappEditComponent_Host0,renderType_ConsumerappEditComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConsumerappEditComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConsumerappEditComponent_0_4 = new Wrapper_ConsumerappEditComponent(this.parentInjector.get(import8.Router),this.parentInjector.get(import9.ConsumerAppService),this.parentInjector.get(import10.ActivatedRoute),this.parentInjector.get(import11.Md2Toast),this.parentInjector.get(import12.Location),this.parentInjector.get(import13.LoaderService));
    this._appEl_0.initComponent(this._ConsumerappEditComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ConsumerappEditComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConsumerappEditComponent) && (0 === requestNodeIndex))) { return this._ConsumerappEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConsumerappEditComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConsumerappEditComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ConsumerappEditComponent_Host === (null as any))) { (renderType_ConsumerappEditComponent_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConsumerappEditComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConsumerappEditComponentNgFactory:import15.ComponentFactory<import0.ConsumerappEditComponent> = new import15.ComponentFactory<import0.ConsumerappEditComponent>('ng-component',viewFactory_ConsumerappEditComponent_Host0,import0.ConsumerappEditComponent);
const styles_ConsumerappEditComponent:any[] = ([] as any[]);
var renderType_ConsumerappEditComponent:import2.RenderComponentType = (null as any);
class _View_ConsumerappEditComponent0 extends import1.AppView<import0.ConsumerappEditComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _MdButton_12_4:import16.Wrapper_MdButton;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _NgForm_20_3:import17.Wrapper_NgForm;
  _ControlContainer_20_4:any;
  _NgControlStatusGroup_20_5:import18.Wrapper_NgControlStatusGroup;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _MdInput_26_4:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_26_5:any[];
  _NgModel_26_6:import20.Wrapper_NgModel;
  _NgControl_26_7:any;
  _NgControlStatus_26_8:import18.Wrapper_NgControlStatus;
  _StyleCompatibility_26_9:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_26_0:import22.QueryList<any>;
  _query_MdHint_26_1:import22.QueryList<any>;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _MdInput_31_4:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_31_5:any[];
  _NgModel_31_6:import20.Wrapper_NgModel;
  _NgControl_31_7:any;
  _NgControlStatus_31_8:import18.Wrapper_NgControlStatus;
  _StyleCompatibility_31_9:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_31_0:import22.QueryList<any>;
  _query_MdHint_31_1:import22.QueryList<any>;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _RequiredValidator_39_4:import23.Wrapper_RequiredValidator;
  _MaxLengthValidator_39_5:import23.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_39_6:any[];
  _MdInput_39_7:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_39_8:any[];
  _NgModel_39_9:import20.Wrapper_NgModel;
  _NgControl_39_10:any;
  _NgControlStatus_39_11:import18.Wrapper_NgControlStatus;
  _StyleCompatibility_39_12:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_39_0:import22.QueryList<any>;
  _query_MdHint_39_1:import22.QueryList<any>;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _RequiredValidator_47_4:import23.Wrapper_RequiredValidator;
  _MaxLengthValidator_47_5:import23.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_47_6:any[];
  _MdInput_47_7:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_47_8:any[];
  _NgModel_47_9:import20.Wrapper_NgModel;
  _NgControl_47_10:any;
  _NgControlStatus_47_11:import18.Wrapper_NgControlStatus;
  _StyleCompatibility_47_12:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_47_0:import22.QueryList<any>;
  _query_MdHint_47_1:import22.QueryList<any>;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import3.AppElement;
  _RequiredValidator_56_4:import23.Wrapper_RequiredValidator;
  _MaxLengthValidator_56_5:import23.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_56_6:any[];
  _MdInput_56_7:import19.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_56_8:any[];
  _NgModel_56_9:import20.Wrapper_NgModel;
  _NgControl_56_10:any;
  _NgControlStatus_56_11:import18.Wrapper_NgControlStatus;
  _StyleCompatibility_56_12:import21.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_56_0:import22.QueryList<any>;
  _query_MdHint_56_1:import22.QueryList<any>;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  /*private*/ _appEl_64:import3.AppElement;
  _MdButton_64_4:import16.Wrapper_MdButton;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_57:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_82:any;
  /*private*/ _expr_83:any;
  /*private*/ _expr_87:any;
  /*private*/ _expr_89:any;
  /*private*/ _expr_94:any;
  /*private*/ _expr_97:any;
  /*private*/ _expr_98:any;
  /*private*/ _expr_99:any;
  /*private*/ _expr_100:any;
  /*private*/ _expr_101:any;
  /*private*/ _expr_102:any;
  /*private*/ _expr_103:any;
  /*private*/ _expr_108:any;
  /*private*/ _expr_109:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumerappEditComponent0,renderType_ConsumerappEditComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','consumer-edit');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title-block');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','title in_block items');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Edit Consumer App',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','text-right items');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn-back btn-green');
    this.renderer.setElementAttribute(this._el_12,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_12,'type','submit');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import16.viewFactory_MdButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._MdButton_12_4 = new import16.Wrapper_MdButton(new import24.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._MdButton_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),' ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','material-icons');
    this._text_15 = this.renderer.createText(this._el_14,'arrow_back',(null as any));
    this._text_16 = this.renderer.createText((null as any),'Back',(null as any));
      compView_12.create(this._MdButton_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_20_3 = new import17.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_20_4 = this._NgForm_20_3.context;
    this._NgControlStatusGroup_20_5 = new import18.Wrapper_NgControlStatusGroup(this._ControlContainer_20_4);
    this._text_21 = this.renderer.createText(this._el_20,'\n\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-group d-flex');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','half-width mr-25');
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','full-width');
    this.renderer.setElementAttribute(this._el_26,'name','AuthId');
    this.renderer.setElementAttribute(this._el_26,'placeholder','Auth Id');
    this._appEl_26 = new import3.AppElement(26,24,this,this._el_26);
    var compView_26:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(26),this._appEl_26);
    this._MdInput_26_4 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_26_5 = [this._MdInput_26_4.context];
    this._NgModel_26_6 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_26_5);
    this._NgControl_26_7 = this._NgModel_26_6.context;
    this._NgControlStatus_26_8 = new import18.Wrapper_NgControlStatus(this._NgControl_26_7);
    this._StyleCompatibility_26_9 = new import21.Wrapper_StyleCompatibility(this.renderer,new import24.ElementRef(this._el_26));
    this._query_MdPlaceholder_26_0 = new import22.QueryList<any>();
    this._query_MdHint_26_1 = new import22.QueryList<any>();
    this._appEl_26.initComponent(this._MdInput_26_4.context,([] as any[]),compView_26);
    this._query_MdPlaceholder_26_0.reset(([] as any[]));
    this._MdInput_26_4.context._placeholderChild = this._query_MdPlaceholder_26_0.first;
    compView_26.create(this._MdInput_26_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n\n            ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','half-width');
    this._text_30 = this.renderer.createText(this._el_29,'\n                ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','full-width');
    this.renderer.setElementAttribute(this._el_31,'name','AuthSecret');
    this.renderer.setElementAttribute(this._el_31,'placeholder','Auth Secret');
    this._appEl_31 = new import3.AppElement(31,29,this,this._el_31);
    var compView_31:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(31),this._appEl_31);
    this._MdInput_31_4 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_31_5 = [this._MdInput_31_4.context];
    this._NgModel_31_6 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_31_5);
    this._NgControl_31_7 = this._NgModel_31_6.context;
    this._NgControlStatus_31_8 = new import18.Wrapper_NgControlStatus(this._NgControl_31_7);
    this._StyleCompatibility_31_9 = new import21.Wrapper_StyleCompatibility(this.renderer,new import24.ElementRef(this._el_31));
    this._query_MdPlaceholder_31_0 = new import22.QueryList<any>();
    this._query_MdHint_31_1 = new import22.QueryList<any>();
    this._appEl_31.initComponent(this._MdInput_31_4.context,([] as any[]),compView_31);
    this._query_MdPlaceholder_31_0.reset(([] as any[]));
    this._MdInput_31_4.context._placeholderChild = this._query_MdPlaceholder_31_0.first;
    compView_31.create(this._MdInput_31_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._text_33 = this.renderer.createText(this._el_22,'\n\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','form-group d-flex');
    this._text_36 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','half-width mr-25');
    this._text_38 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','full-width');
    this.renderer.setElementAttribute(this._el_39,'maxlength','255');
    this.renderer.setElementAttribute(this._el_39,'name','name');
    this.renderer.setElementAttribute(this._el_39,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_39,'required','');
    this._appEl_39 = new import3.AppElement(39,37,this,this._el_39);
    var compView_39:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(39),this._appEl_39);
    this._RequiredValidator_39_4 = new import23.Wrapper_RequiredValidator();
    this._MaxLengthValidator_39_5 = new import23.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_39_6 = [
      this._RequiredValidator_39_4.context,
      this._MaxLengthValidator_39_5.context
    ]
    ;
    this._MdInput_39_7 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_39_8 = [this._MdInput_39_7.context];
    this._NgModel_39_9 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_39_6,(null as any),this._NG_VALUE_ACCESSOR_39_8);
    this._NgControl_39_10 = this._NgModel_39_9.context;
    this._NgControlStatus_39_11 = new import18.Wrapper_NgControlStatus(this._NgControl_39_10);
    this._StyleCompatibility_39_12 = new import21.Wrapper_StyleCompatibility(this.renderer,new import24.ElementRef(this._el_39));
    this._query_MdPlaceholder_39_0 = new import22.QueryList<any>();
    this._query_MdHint_39_1 = new import22.QueryList<any>();
    this._appEl_39.initComponent(this._MdInput_39_7.context,([] as any[]),compView_39);
    this._query_MdPlaceholder_39_0.reset(([] as any[]));
    this._MdInput_39_7.context._placeholderChild = this._query_MdPlaceholder_39_0.first;
    compView_39.create(this._MdInput_39_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_37,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','error');
    this._text_42 = this.renderer.createText(this._el_41,'Name is required',(null as any));
    this._text_43 = this.renderer.createText(this._el_37,'\n\n            ',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'class','half-width ');
    this._text_46 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','full-width');
    this.renderer.setElementAttribute(this._el_47,'maxlength','255');
    this.renderer.setElementAttribute(this._el_47,'name','callbackUrl');
    this.renderer.setElementAttribute(this._el_47,'placeholder','Call Back Url');
    this.renderer.setElementAttribute(this._el_47,'required','');
    this.renderer.setElementAttribute(this._el_47,'type','text');
    this._appEl_47 = new import3.AppElement(47,45,this,this._el_47);
    var compView_47:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(47),this._appEl_47);
    this._RequiredValidator_47_4 = new import23.Wrapper_RequiredValidator();
    this._MaxLengthValidator_47_5 = new import23.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_47_6 = [
      this._RequiredValidator_47_4.context,
      this._MaxLengthValidator_47_5.context
    ]
    ;
    this._MdInput_47_7 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_47_8 = [this._MdInput_47_7.context];
    this._NgModel_47_9 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_47_6,(null as any),this._NG_VALUE_ACCESSOR_47_8);
    this._NgControl_47_10 = this._NgModel_47_9.context;
    this._NgControlStatus_47_11 = new import18.Wrapper_NgControlStatus(this._NgControl_47_10);
    this._StyleCompatibility_47_12 = new import21.Wrapper_StyleCompatibility(this.renderer,new import24.ElementRef(this._el_47));
    this._query_MdPlaceholder_47_0 = new import22.QueryList<any>();
    this._query_MdHint_47_1 = new import22.QueryList<any>();
    this._appEl_47.initComponent(this._MdInput_47_7.context,([] as any[]),compView_47);
    this._query_MdPlaceholder_47_0.reset(([] as any[]));
    this._MdInput_47_7.context._placeholderChild = this._query_MdPlaceholder_47_0.first;
    compView_47.create(this._MdInput_47_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_48 = this.renderer.createText(this._el_45,'\n                ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_45,'div',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','error');
    this._text_50 = this.renderer.createText(this._el_49,'Call Back Url is required',(null as any));
    this._text_51 = this.renderer.createText(this._el_45,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_20,'\n\n\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','form-group');
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','full-width');
    this.renderer.setElementAttribute(this._el_56,'maxlength','1000');
    this.renderer.setElementAttribute(this._el_56,'name','description');
    this.renderer.setElementAttribute(this._el_56,'placeholder','Description');
    this.renderer.setElementAttribute(this._el_56,'required','');
    this._appEl_56 = new import3.AppElement(56,54,this,this._el_56);
    var compView_56:any = import19.viewFactory_MdInput0(this.viewUtils,this.injector(56),this._appEl_56);
    this._RequiredValidator_56_4 = new import23.Wrapper_RequiredValidator();
    this._MaxLengthValidator_56_5 = new import23.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_56_6 = [
      this._RequiredValidator_56_4.context,
      this._MaxLengthValidator_56_5.context
    ]
    ;
    this._MdInput_56_7 = new import19.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_56_8 = [this._MdInput_56_7.context];
    this._NgModel_56_9 = new import20.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_56_6,(null as any),this._NG_VALUE_ACCESSOR_56_8);
    this._NgControl_56_10 = this._NgModel_56_9.context;
    this._NgControlStatus_56_11 = new import18.Wrapper_NgControlStatus(this._NgControl_56_10);
    this._StyleCompatibility_56_12 = new import21.Wrapper_StyleCompatibility(this.renderer,new import24.ElementRef(this._el_56));
    this._query_MdPlaceholder_56_0 = new import22.QueryList<any>();
    this._query_MdHint_56_1 = new import22.QueryList<any>();
    this._appEl_56.initComponent(this._MdInput_56_7.context,([] as any[]),compView_56);
    this._query_MdPlaceholder_56_0.reset(([] as any[]));
    this._MdInput_56_7.context._placeholderChild = this._query_MdPlaceholder_56_0.first;
    compView_56.create(this._MdInput_56_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','error');
    this._text_59 = this.renderer.createText(this._el_58,'Description is required',(null as any));
    this._text_60 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_61 = this.renderer.createText(this._el_20,'\n\n        ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','form-group');
    this.renderer.setElementAttribute(this._el_62,'id','group-btn');
    this._text_63 = this.renderer.createText(this._el_62,'\n            ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_62,'button',(null as any));
    this.renderer.setElementAttribute(this._el_64,'class','btn-green mr-15');
    this.renderer.setElementAttribute(this._el_64,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_64,'type','submit');
    this._appEl_64 = new import3.AppElement(64,62,this,this._el_64);
    var compView_64:any = import16.viewFactory_MdButton0(this.viewUtils,this.injector(64),this._appEl_64);
    this._MdButton_64_4 = new import16.Wrapper_MdButton(new import24.ElementRef(this._el_64),this.renderer);
    this._appEl_64.initComponent(this._MdButton_64_4.context,([] as any[]),compView_64);
    this._text_65 = this.renderer.createText((null as any),'Update',(null as any));
    compView_64.create(this._MdButton_64_4.context,[([] as any[]).concat([this._text_65])],(null as any));
    this._text_66 = this.renderer.createText(this._el_62,'\n            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_62,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_3.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_20,'submit',this.eventHandler(this._handle_submit_20_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_20,'reset',this.eventHandler(this._handle_reset_20_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_1.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_26_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_31,'ngModelChange',this.eventHandler(this._handle_ngModelChange_31_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_31,'click',this.eventHandler(this._handle_click_31_1.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_31_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_31_0.bind(this)));
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_39,'ngModelChange',this.eventHandler(this._handle_ngModelChange_39_0.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_1.bind(this)));
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_39_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_39_0.bind(this)));
    this._expr_56 = import7.UNINITIALIZED;
    this._expr_57 = import7.UNINITIALIZED;
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_47,'ngModelChange',this.eventHandler(this._handle_ngModelChange_47_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_1.bind(this)));
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_74 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_47_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_47_0.bind(this)));
    this._expr_77 = import7.UNINITIALIZED;
    this._expr_78 = import7.UNINITIALIZED;
    this._expr_79 = import7.UNINITIALIZED;
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_81 = import7.UNINITIALIZED;
    this._expr_82 = import7.UNINITIALIZED;
    this._expr_83 = import7.UNINITIALIZED;
    var disposable_14:Function = this.renderer.listen(this._el_56,'ngModelChange',this.eventHandler(this._handle_ngModelChange_56_0.bind(this)));
    var disposable_15:Function = this.renderer.listen(this._el_56,'click',this.eventHandler(this._handle_click_56_1.bind(this)));
    this._expr_87 = import7.UNINITIALIZED;
    this._expr_89 = import7.UNINITIALIZED;
    this._expr_94 = import7.UNINITIALIZED;
    const subscription_4:any = this._NgModel_56_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_56_0.bind(this)));
    this._expr_97 = import7.UNINITIALIZED;
    this._expr_98 = import7.UNINITIALIZED;
    this._expr_99 = import7.UNINITIALIZED;
    this._expr_100 = import7.UNINITIALIZED;
    this._expr_101 = import7.UNINITIALIZED;
    this._expr_102 = import7.UNINITIALIZED;
    this._expr_103 = import7.UNINITIALIZED;
    this._expr_108 = import7.UNINITIALIZED;
    var disposable_16:Function = this.renderer.listen(this._el_64,'click',this.eventHandler(this._handle_click_64_0.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_64,'mousedown',this.eventHandler(this._handle_mousedown_64_1.bind(this)));
    var disposable_18:Function = this.renderer.listen(this._el_64,'focus',this.eventHandler(this._handle_focus_64_2.bind(this)));
    var disposable_19:Function = this.renderer.listen(this._el_64,'blur',this.eventHandler(this._handle_blur_64_3.bind(this)));
    this._expr_109 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17,
      disposable_18,
      disposable_19
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_12_4.context; }
    if (((token === import26.MdInput) && (26 === requestNodeIndex))) { return this._MdInput_26_4.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_5; }
    if (((token === import28.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_6.context; }
    if (((token === import29.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_7; }
    if (((token === import30.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_8.context; }
    if (((token === import31.StyleCompatibility) && (26 === requestNodeIndex))) { return this._StyleCompatibility_26_9.context; }
    if (((token === import26.MdInput) && (31 === requestNodeIndex))) { return this._MdInput_31_4.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (31 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_31_5; }
    if (((token === import28.NgModel) && (31 === requestNodeIndex))) { return this._NgModel_31_6.context; }
    if (((token === import29.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_7; }
    if (((token === import30.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_8.context; }
    if (((token === import31.StyleCompatibility) && (31 === requestNodeIndex))) { return this._StyleCompatibility_31_9.context; }
    if (((token === import32.RequiredValidator) && (39 === requestNodeIndex))) { return this._RequiredValidator_39_4.context; }
    if (((token === import32.MaxLengthValidator) && (39 === requestNodeIndex))) { return this._MaxLengthValidator_39_5.context; }
    if (((token === import33.NG_VALIDATORS) && (39 === requestNodeIndex))) { return this._NG_VALIDATORS_39_6; }
    if (((token === import26.MdInput) && (39 === requestNodeIndex))) { return this._MdInput_39_7.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (39 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_39_8; }
    if (((token === import28.NgModel) && (39 === requestNodeIndex))) { return this._NgModel_39_9.context; }
    if (((token === import29.NgControl) && (39 === requestNodeIndex))) { return this._NgControl_39_10; }
    if (((token === import30.NgControlStatus) && (39 === requestNodeIndex))) { return this._NgControlStatus_39_11.context; }
    if (((token === import31.StyleCompatibility) && (39 === requestNodeIndex))) { return this._StyleCompatibility_39_12.context; }
    if (((token === import32.RequiredValidator) && (47 === requestNodeIndex))) { return this._RequiredValidator_47_4.context; }
    if (((token === import32.MaxLengthValidator) && (47 === requestNodeIndex))) { return this._MaxLengthValidator_47_5.context; }
    if (((token === import33.NG_VALIDATORS) && (47 === requestNodeIndex))) { return this._NG_VALIDATORS_47_6; }
    if (((token === import26.MdInput) && (47 === requestNodeIndex))) { return this._MdInput_47_7.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (47 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_47_8; }
    if (((token === import28.NgModel) && (47 === requestNodeIndex))) { return this._NgModel_47_9.context; }
    if (((token === import29.NgControl) && (47 === requestNodeIndex))) { return this._NgControl_47_10; }
    if (((token === import30.NgControlStatus) && (47 === requestNodeIndex))) { return this._NgControlStatus_47_11.context; }
    if (((token === import31.StyleCompatibility) && (47 === requestNodeIndex))) { return this._StyleCompatibility_47_12.context; }
    if (((token === import32.RequiredValidator) && (56 === requestNodeIndex))) { return this._RequiredValidator_56_4.context; }
    if (((token === import32.MaxLengthValidator) && (56 === requestNodeIndex))) { return this._MaxLengthValidator_56_5.context; }
    if (((token === import33.NG_VALIDATORS) && (56 === requestNodeIndex))) { return this._NG_VALIDATORS_56_6; }
    if (((token === import26.MdInput) && (56 === requestNodeIndex))) { return this._MdInput_56_7.context; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (56 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_56_8; }
    if (((token === import28.NgModel) && (56 === requestNodeIndex))) { return this._NgModel_56_9.context; }
    if (((token === import29.NgControl) && (56 === requestNodeIndex))) { return this._NgControl_56_10; }
    if (((token === import30.NgControlStatus) && (56 === requestNodeIndex))) { return this._NgControlStatus_56_11.context; }
    if (((token === import31.StyleCompatibility) && (56 === requestNodeIndex))) { return this._StyleCompatibility_56_12.context; }
    if (((token === import25.MdButton) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._MdButton_64_4.context; }
    if (((token === import34.NgForm) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._NgForm_20_3.context; }
    if (((token === import35.ControlContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._ControlContainer_20_4; }
    if (((token === import30.NgControlStatusGroup) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._NgControlStatusGroup_20_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._NgForm_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._NgControlStatusGroup_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_15:any = true;
    this._MdInput_26_4.check_disabled(currVal_15,throwOnChange,false);
    const currVal_16:any = 'Auth Id';
    this._MdInput_26_4.check_placeholder(currVal_16,throwOnChange,false);
    const currVal_17:any = 'AuthId';
    this._MdInput_26_4.check_name(currVal_17,throwOnChange,false);
    this._MdInput_26_4.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_19:any = 'AuthId';
    this._NgModel_26_6.check_name(currVal_19,throwOnChange,false);
    const currVal_20:any = true;
    this._NgModel_26_6.check_isDisabled(currVal_20,throwOnChange,false);
    const currVal_21:any = this.context.consumerModel.AuthId;
    this._NgModel_26_6.check_model(currVal_21,throwOnChange,false);
    this._NgModel_26_6.detectChangesInternal(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_8.detectChangesInternal(this,this._el_26,throwOnChange);
    this._StyleCompatibility_26_9.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_30:any = true;
    this._MdInput_31_4.check_disabled(currVal_30,throwOnChange,false);
    const currVal_31:any = 'Auth Secret';
    this._MdInput_31_4.check_placeholder(currVal_31,throwOnChange,false);
    const currVal_32:any = 'AuthSecret';
    this._MdInput_31_4.check_name(currVal_32,throwOnChange,false);
    this._MdInput_31_4.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_34:any = 'AuthSecret';
    this._NgModel_31_6.check_name(currVal_34,throwOnChange,false);
    const currVal_35:any = true;
    this._NgModel_31_6.check_isDisabled(currVal_35,throwOnChange,false);
    const currVal_36:any = this.context.consumerModel.AuthSecret;
    this._NgModel_31_6.check_model(currVal_36,throwOnChange,false);
    this._NgModel_31_6.detectChangesInternal(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_8.detectChangesInternal(this,this._el_31,throwOnChange);
    this._StyleCompatibility_31_9.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_45:any = '';
    this._RequiredValidator_39_4.check_required(currVal_45,throwOnChange,false);
    this._RequiredValidator_39_4.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_47:any = '255';
    this._MaxLengthValidator_39_5.check_maxlength(currVal_47,throwOnChange,false);
    this._MaxLengthValidator_39_5.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_49:any = '255';
    this._MdInput_39_7.check_maxlength(currVal_49,throwOnChange,false);
    const currVal_50:any = 'Name';
    this._MdInput_39_7.check_placeholder(currVal_50,throwOnChange,false);
    const currVal_51:any = '';
    this._MdInput_39_7.check_required(currVal_51,throwOnChange,false);
    const currVal_52:any = 'name';
    this._MdInput_39_7.check_name(currVal_52,throwOnChange,false);
    this._MdInput_39_7.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_54:any = 'name';
    this._NgModel_39_9.check_name(currVal_54,throwOnChange,false);
    const currVal_55:any = this.context.consumerModel.Name;
    this._NgModel_39_9.check_model(currVal_55,throwOnChange,false);
    this._NgModel_39_9.detectChangesInternal(this,this._el_39,throwOnChange);
    this._NgControlStatus_39_11.detectChangesInternal(this,this._el_39,throwOnChange);
    this._StyleCompatibility_39_12.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_65:any = '';
    this._RequiredValidator_47_4.check_required(currVal_65,throwOnChange,false);
    this._RequiredValidator_47_4.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_67:any = '255';
    this._MaxLengthValidator_47_5.check_maxlength(currVal_67,throwOnChange,false);
    this._MaxLengthValidator_47_5.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_69:any = '255';
    this._MdInput_47_7.check_maxlength(currVal_69,throwOnChange,false);
    const currVal_70:any = 'Call Back Url';
    this._MdInput_47_7.check_placeholder(currVal_70,throwOnChange,false);
    const currVal_71:any = '';
    this._MdInput_47_7.check_required(currVal_71,throwOnChange,false);
    const currVal_72:any = 'text';
    this._MdInput_47_7.check_type(currVal_72,throwOnChange,false);
    const currVal_73:any = 'callbackUrl';
    this._MdInput_47_7.check_name(currVal_73,throwOnChange,false);
    this._MdInput_47_7.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_75:any = 'callbackUrl';
    this._NgModel_47_9.check_name(currVal_75,throwOnChange,false);
    const currVal_76:any = this.context.consumerModel.CallbackUrl;
    this._NgModel_47_9.check_model(currVal_76,throwOnChange,false);
    this._NgModel_47_9.detectChangesInternal(this,this._el_47,throwOnChange);
    this._NgControlStatus_47_11.detectChangesInternal(this,this._el_47,throwOnChange);
    this._StyleCompatibility_47_12.detectChangesInternal(this,this._el_47,throwOnChange);
    const currVal_86:any = '';
    this._RequiredValidator_56_4.check_required(currVal_86,throwOnChange,false);
    this._RequiredValidator_56_4.detectChangesInternal(this,this._el_56,throwOnChange);
    const currVal_88:any = '1000';
    this._MaxLengthValidator_56_5.check_maxlength(currVal_88,throwOnChange,false);
    this._MaxLengthValidator_56_5.detectChangesInternal(this,this._el_56,throwOnChange);
    const currVal_90:any = '1000';
    this._MdInput_56_7.check_maxlength(currVal_90,throwOnChange,false);
    const currVal_91:any = 'Description';
    this._MdInput_56_7.check_placeholder(currVal_91,throwOnChange,false);
    const currVal_92:any = '';
    this._MdInput_56_7.check_required(currVal_92,throwOnChange,false);
    const currVal_93:any = 'description';
    this._MdInput_56_7.check_name(currVal_93,throwOnChange,false);
    this._MdInput_56_7.detectChangesInternal(this,this._el_56,throwOnChange);
    const currVal_95:any = 'description';
    this._NgModel_56_9.check_name(currVal_95,throwOnChange,false);
    const currVal_96:any = this.context.consumerModel.Description;
    this._NgModel_56_9.check_model(currVal_96,throwOnChange,false);
    this._NgModel_56_9.detectChangesInternal(this,this._el_56,throwOnChange);
    this._NgControlStatus_56_11.detectChangesInternal(this,this._el_56,throwOnChange);
    this._StyleCompatibility_56_12.detectChangesInternal(this,this._el_56,throwOnChange);
    if (this._MdButton_64_4.detectChangesInternal(this,this._el_64,throwOnChange)) { this._appEl_64.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_26_1.dirty) {
        this._query_MdHint_26_1.reset(([] as any[]));
        this._MdInput_26_4.context._hintChildren = this._query_MdHint_26_1;
        this._query_MdHint_26_1.notifyOnChanges();
      }
      if (this._query_MdHint_31_1.dirty) {
        this._query_MdHint_31_1.reset(([] as any[]));
        this._MdInput_31_4.context._hintChildren = this._query_MdHint_31_1;
        this._query_MdHint_31_1.notifyOnChanges();
      }
      if (this._query_MdHint_39_1.dirty) {
        this._query_MdHint_39_1.reset(([] as any[]));
        this._MdInput_39_7.context._hintChildren = this._query_MdHint_39_1;
        this._query_MdHint_39_1.notifyOnChanges();
      }
      if (this._query_MdHint_47_1.dirty) {
        this._query_MdHint_47_1.reset(([] as any[]));
        this._MdInput_47_7.context._hintChildren = this._query_MdHint_47_1;
        this._query_MdHint_47_1.notifyOnChanges();
      }
      if (this._query_MdHint_56_1.dirty) {
        this._query_MdHint_56_1.reset(([] as any[]));
        this._MdInput_56_7.context._hintChildren = this._query_MdHint_56_1;
        this._query_MdHint_56_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_26_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_31_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_39_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_47_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_56_7.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._MdButton_12_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_12,'md-button-focus',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatusGroup_20_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_20_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_20_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_20_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_20_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_20_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_18:any = this._MdInput_26_4.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_26,'align',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._NgControlStatus_26_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_26_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_26_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_26_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_26_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_26_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_33:any = this._MdInput_31_4.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementAttribute(this._el_31,'align',((currVal_33 == (null as any))? (null as any): currVal_33.toString()));
      this._expr_33 = currVal_33;
    }
    const currVal_37:any = this._NgControlStatus_31_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_31,'ng-untouched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_31_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_31,'ng-touched',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_31_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_31,'ng-pristine',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_31_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_31,'ng-dirty',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_31_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_31,'ng-valid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_31_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_31,'ng-invalid',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_46:any = (this._RequiredValidator_39_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementAttribute(this._el_39,'required',((currVal_46 == (null as any))? (null as any): currVal_46.toString()));
      this._expr_46 = currVal_46;
    }
    const currVal_48:any = (this._MaxLengthValidator_39_5.context.maxlength? this._MaxLengthValidator_39_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementAttribute(this._el_39,'maxlength',((currVal_48 == (null as any))? (null as any): currVal_48.toString()));
      this._expr_48 = currVal_48;
    }
    const currVal_53:any = this._MdInput_39_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementAttribute(this._el_39,'align',((currVal_53 == (null as any))? (null as any): currVal_53.toString()));
      this._expr_53 = currVal_53;
    }
    const currVal_56:any = this._NgControlStatus_39_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_39,'ng-untouched',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_57:any = this._NgControlStatus_39_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_57,currVal_57)) {
      this.renderer.setElementClass(this._el_39,'ng-touched',currVal_57);
      this._expr_57 = currVal_57;
    }
    const currVal_58:any = this._NgControlStatus_39_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementClass(this._el_39,'ng-pristine',currVal_58);
      this._expr_58 = currVal_58;
    }
    const currVal_59:any = this._NgControlStatus_39_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this.renderer.setElementClass(this._el_39,'ng-dirty',currVal_59);
      this._expr_59 = currVal_59;
    }
    const currVal_60:any = this._NgControlStatus_39_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementClass(this._el_39,'ng-valid',currVal_60);
      this._expr_60 = currVal_60;
    }
    const currVal_61:any = this._NgControlStatus_39_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementClass(this._el_39,'ng-invalid',currVal_61);
      this._expr_61 = currVal_61;
    }
    const currVal_62:boolean = !((this._NgModel_39_9.context.touched && !this._NgModel_39_9.context.valid) && this._NgModel_39_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementProperty(this._el_41,'hidden',currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_66:any = (this._RequiredValidator_47_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementAttribute(this._el_47,'required',((currVal_66 == (null as any))? (null as any): currVal_66.toString()));
      this._expr_66 = currVal_66;
    }
    const currVal_68:any = (this._MaxLengthValidator_47_5.context.maxlength? this._MaxLengthValidator_47_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementAttribute(this._el_47,'maxlength',((currVal_68 == (null as any))? (null as any): currVal_68.toString()));
      this._expr_68 = currVal_68;
    }
    const currVal_74:any = this._MdInput_47_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementAttribute(this._el_47,'align',((currVal_74 == (null as any))? (null as any): currVal_74.toString()));
      this._expr_74 = currVal_74;
    }
    const currVal_77:any = this._NgControlStatus_47_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setElementClass(this._el_47,'ng-untouched',currVal_77);
      this._expr_77 = currVal_77;
    }
    const currVal_78:any = this._NgControlStatus_47_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementClass(this._el_47,'ng-touched',currVal_78);
      this._expr_78 = currVal_78;
    }
    const currVal_79:any = this._NgControlStatus_47_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementClass(this._el_47,'ng-pristine',currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = this._NgControlStatus_47_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementClass(this._el_47,'ng-dirty',currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = this._NgControlStatus_47_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setElementClass(this._el_47,'ng-valid',currVal_81);
      this._expr_81 = currVal_81;
    }
    const currVal_82:any = this._NgControlStatus_47_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementClass(this._el_47,'ng-invalid',currVal_82);
      this._expr_82 = currVal_82;
    }
    const currVal_83:boolean = !((this._NgModel_47_9.context.touched && !this._NgModel_47_9.context.valid) && this._NgModel_47_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setElementProperty(this._el_49,'hidden',currVal_83);
      this._expr_83 = currVal_83;
    }
    const currVal_87:any = (this._RequiredValidator_56_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_87,currVal_87)) {
      this.renderer.setElementAttribute(this._el_56,'required',((currVal_87 == (null as any))? (null as any): currVal_87.toString()));
      this._expr_87 = currVal_87;
    }
    const currVal_89:any = (this._MaxLengthValidator_56_5.context.maxlength? this._MaxLengthValidator_56_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_89,currVal_89)) {
      this.renderer.setElementAttribute(this._el_56,'maxlength',((currVal_89 == (null as any))? (null as any): currVal_89.toString()));
      this._expr_89 = currVal_89;
    }
    const currVal_94:any = this._MdInput_56_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_94,currVal_94)) {
      this.renderer.setElementAttribute(this._el_56,'align',((currVal_94 == (null as any))? (null as any): currVal_94.toString()));
      this._expr_94 = currVal_94;
    }
    const currVal_97:any = this._NgControlStatus_56_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_97,currVal_97)) {
      this.renderer.setElementClass(this._el_56,'ng-untouched',currVal_97);
      this._expr_97 = currVal_97;
    }
    const currVal_98:any = this._NgControlStatus_56_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_98,currVal_98)) {
      this.renderer.setElementClass(this._el_56,'ng-touched',currVal_98);
      this._expr_98 = currVal_98;
    }
    const currVal_99:any = this._NgControlStatus_56_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_99,currVal_99)) {
      this.renderer.setElementClass(this._el_56,'ng-pristine',currVal_99);
      this._expr_99 = currVal_99;
    }
    const currVal_100:any = this._NgControlStatus_56_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_100,currVal_100)) {
      this.renderer.setElementClass(this._el_56,'ng-dirty',currVal_100);
      this._expr_100 = currVal_100;
    }
    const currVal_101:any = this._NgControlStatus_56_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_101,currVal_101)) {
      this.renderer.setElementClass(this._el_56,'ng-valid',currVal_101);
      this._expr_101 = currVal_101;
    }
    const currVal_102:any = this._NgControlStatus_56_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_102,currVal_102)) {
      this.renderer.setElementClass(this._el_56,'ng-invalid',currVal_102);
      this._expr_102 = currVal_102;
    }
    const currVal_103:boolean = !((this._NgModel_56_9.context.touched && !this._NgModel_56_9.context.valid) && this._NgModel_56_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_103,currVal_103)) {
      this.renderer.setElementProperty(this._el_58,'hidden',currVal_103);
      this._expr_103 = currVal_103;
    }
    const currVal_108:boolean = !this._NgForm_20_3.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_108,currVal_108)) {
      this.renderer.setElementProperty(this._el_64,'disabled',currVal_108);
      this._expr_108 = currVal_108;
    }
    const currVal_109:any = this._MdButton_64_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_109,currVal_109)) {
      this.renderer.setElementClass(this._el_64,'md-button-focus',currVal_109);
      this._expr_109 = currVal_109;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_26_6.context.ngOnDestroy();
    this._NgModel_31_6.context.ngOnDestroy();
    this._NgModel_39_9.context.ngOnDestroy();
    this._NgModel_47_9.context.ngOnDestroy();
    this._NgModel_56_9.context.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.cancel()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_1($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_2($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_3($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.AuthId = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_1($event:any):boolean {
    this._appEl_26.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_26_4.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.AuthSecret = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_31_1($event:any):boolean {
    this._appEl_31.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_31_4.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.Name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_1($event:any):boolean {
    this._appEl_39.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_39_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.CallbackUrl = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_1($event:any):boolean {
    this._appEl_47.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_47_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_56_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.consumerModel.Description = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_56_1($event:any):boolean {
    this._appEl_56.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_56_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_click_64_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateApps(this.context.consumerModel)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_64_1($event:any):boolean {
    this._appEl_64.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_64_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_64_2($event:any):boolean {
    this._appEl_64.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_64_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_64_3($event:any):boolean {
    this._appEl_64.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_64_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ConsumerappEditComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ConsumerappEditComponent> {
  if ((renderType_ConsumerappEditComponent === (null as any))) { (renderType_ConsumerappEditComponent = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_ConsumerappEditComponent,{})); }
  return new _View_ConsumerappEditComponent0(viewUtils,parentInjector,declarationEl);
}