/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/project/project-view/project-view.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../../app/project/project.service';
import * as import11 from '@angular/common/src/location/location';
import * as import12 from 'md2/toast/toast';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../../node_modules/@angular2-material/button/button.ngfactory';
import * as import16 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular2-material/button/button';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '../../../node_modules/@angular2-material/checkbox/checkbox.ngfactory';
import * as import22 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import24 from '../../../node_modules/md2/core/compatibility/style-compatibility.ngfactory';
import * as import25 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import26 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import27 from '@angular2-material/checkbox/checkbox';
import * as import28 from '@angular/forms/src/directives/control_value_accessor';
import * as import29 from '@angular/forms/src/directives/ng_model';
import * as import30 from '@angular/forms/src/directives/ng_control';
import * as import31 from '@angular/forms/src/directives/ng_control_status';
import * as import32 from 'md2/core/compatibility/style-compatibility';
import * as import33 from '@angular/common/src/directives/ng_for';
export class Wrapper_ProjectViewComponent {
  context:import0.ProjectViewComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.ProjectViewComponent(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_ProjectViewComponent_Host:import2.RenderComponentType = (null as any);
class _View_ProjectViewComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ProjectViewComponent_0_4:Wrapper_ProjectViewComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent_Host0,renderType_ProjectViewComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProjectViewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProjectViewComponent_0_4 = new Wrapper_ProjectViewComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.ProjectService),this.parentInjector.get(import11.Location),this.parentInjector.get(import12.Md2Toast));
    this._appEl_0.initComponent(this._ProjectViewComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ProjectViewComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProjectViewComponent) && (0 === requestNodeIndex))) { return this._ProjectViewComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProjectViewComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProjectViewComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ProjectViewComponent_Host === (null as any))) { (renderType_ProjectViewComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ProjectViewComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProjectViewComponentNgFactory:import14.ComponentFactory<import0.ProjectViewComponent> = new import14.ComponentFactory<import0.ProjectViewComponent>('ng-component',viewFactory_ProjectViewComponent_Host0,import0.ProjectViewComponent);
const styles_ProjectViewComponent:any[] = ([] as any[]);
var renderType_ProjectViewComponent:import2.RenderComponentType = (null as any);
class _View_ProjectViewComponent0 extends import1.AppView<import0.ProjectViewComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _MdButton_12_4:import15.Wrapper_MdButton;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import16.Wrapper_NgIf;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent0,renderType_ProjectViewComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','project-edit');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title-block d-flex');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','title items');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'View Project',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','text-right items');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn-back btn-green');
    this.renderer.setElementAttribute(this._el_12,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_12,'type','submit');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import15.viewFactory_MdButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._MdButton_12_4 = new import15.Wrapper_MdButton(new import17.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._MdButton_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),' ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','material-icons');
    this._text_15 = this.renderer.createText(this._el_14,'arrow_back',(null as any));
    this._text_16 = this.renderer.createText((null as any),'Back',(null as any));
      compView_12.create(this._MdButton_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_20 = new import3.AppElement(20,0,this,this._anchor_20);
    this._TemplateRef_20_5 = new import18.TemplateRef_(this._appEl_20,viewFactory_ProjectViewComponent1);
    this._NgIf_20_6 = new import16.Wrapper_NgIf(this._appEl_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_3.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_12_4.context; }
    if (((token === import18.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import20.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    const currVal_5:any = this.context.project;
    this._NgIf_20_6.check_ngIf(currVal_5,throwOnChange,false);
    this._NgIf_20_6.detectChangesInternal(this,this._anchor_20,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._MdButton_12_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_12,'md-button-focus',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.gotoProjects()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_1($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_2($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_3($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ProjectViewComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ProjectViewComponent> {
  if ((renderType_ProjectViewComponent === (null as any))) { (renderType_ProjectViewComponent = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ProjectViewComponent,{})); }
  return new _View_ProjectViewComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _MdCheckbox_19_4:import21.Wrapper_MdCheckbox;
  _NG_VALUE_ACCESSOR_19_5:any[];
  _NgModel_19_6:import22.Wrapper_NgModel;
  _NgControl_19_7:any;
  _NgControlStatus_19_8:import23.Wrapper_NgControlStatus;
  _StyleCompatibility_19_9:import24.Wrapper_StyleCompatibility;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _anchor_62:any;
  /*private*/ _appEl_62:import3.AppElement;
  _TemplateRef_62_5:any;
  _NgFor_62_6:import25.Wrapper_NgFor;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent1,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','form-group');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'label',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Name:',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','form-group');
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'label',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                Slack Channel Name:\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n\n\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','form-group');
    this._text_15 = this.renderer.createText(this._el_14,'\n\n\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'label',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n                IsActive:\n            ',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_14,'md-checkbox',(null as any));
    this.renderer.setElementAttribute(this._el_19,'disabled','true');
    this.renderer.setElementAttribute(this._el_19,'id','chckbox');
    this.renderer.setElementAttribute(this._el_19,'name','IsActive');
    this.renderer.setElementAttribute(this._el_19,'type','checkbox');
    this._appEl_19 = new import3.AppElement(19,14,this,this._el_19);
    var compView_19:any = import21.viewFactory_MdCheckbox0(this.viewUtils,this.injector(19),this._appEl_19);
    this._MdCheckbox_19_4 = new import21.Wrapper_MdCheckbox(this.renderer,new import17.ElementRef(this._el_19));
    this._NG_VALUE_ACCESSOR_19_5 = [this._MdCheckbox_19_4.context];
    this._NgModel_19_6 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_19_5);
    this._NgControl_19_7 = this._NgModel_19_6.context;
    this._NgControlStatus_19_8 = new import23.Wrapper_NgControlStatus(this._NgControl_19_7);
    this._StyleCompatibility_19_9 = new import24.Wrapper_StyleCompatibility(this.renderer,new import17.ElementRef(this._el_19));
    this._appEl_19.initComponent(this._MdCheckbox_19_4.context,([] as any[]),compView_19);
    compView_19.create(this._MdCheckbox_19_4.context,[([] as any[])],(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n\n        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n\n\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','half-width');
    this._text_23 = this.renderer.createText(this._el_22,'\n\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'label',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Team Leader:',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n\n\n\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','half-width');
    this._text_29 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'table',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'tbody',(null as any));
    this._el_33 = this.renderer.createElement(this._el_32,'tr',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'td',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_38 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._text_39 = this.renderer.createText(this._el_28,'\n\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'br',(null as any));
    this._text_44 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','half-width');
    this._text_47 = this.renderer.createText(this._el_46,'\n\n            ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'label',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'List Of Team Members:',(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'\n            ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'br',(null as any));
    this._text_55 = this.renderer.createText(this._el_52,'\n        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','half-width');
    this._text_58 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'table',(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n                ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'tbody',(null as any));
    this._anchor_62 = this.renderer.createTemplateAnchor(this._el_61,(null as any));
    this._appEl_62 = new import3.AppElement(62,61,this,this._anchor_62);
    this._TemplateRef_62_5 = new import18.TemplateRef_(this._appEl_62,viewFactory_ProjectViewComponent2);
    this._NgFor_62_6 = new import25.Wrapper_NgFor(this._appEl_62.vcRef,this._TemplateRef_62_5,this.parent.parentInjector.get(import26.IterableDiffers),this.parent.ref);
    this._text_63 = this.renderer.createText(this._el_61,'\n            ',(null as any));
    this._text_64 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_0,'\n\n\n\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_19,'ngModelChange',this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_19_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_19_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._anchor_62,
      this._text_63,
      this._text_64,
      this._text_65
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.MdCheckbox) && (19 === requestNodeIndex))) { return this._MdCheckbox_19_4.context; }
    if (((token === import28.NG_VALUE_ACCESSOR) && (19 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_19_5; }
    if (((token === import29.NgModel) && (19 === requestNodeIndex))) { return this._NgModel_19_6.context; }
    if (((token === import30.NgControl) && (19 === requestNodeIndex))) { return this._NgControl_19_7; }
    if (((token === import31.NgControlStatus) && (19 === requestNodeIndex))) { return this._NgControlStatus_19_8.context; }
    if (((token === import32.StyleCompatibility) && (19 === requestNodeIndex))) { return this._StyleCompatibility_19_9.context; }
    if (((token === import18.TemplateRef) && (62 === requestNodeIndex))) { return this._TemplateRef_62_5; }
    if (((token === import33.NgFor) && (62 === requestNodeIndex))) { return this._NgFor_62_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_3:any = 'chckbox';
    this._MdCheckbox_19_4.check_id(currVal_3,throwOnChange,false);
    const currVal_4:any = 'true';
    this._MdCheckbox_19_4.check_disabled(currVal_4,throwOnChange,false);
    const currVal_5:any = 'IsActive';
    this._MdCheckbox_19_4.check_name(currVal_5,throwOnChange,false);
    if (this._MdCheckbox_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    const currVal_11:any = 'IsActive';
    this._NgModel_19_6.check_name(currVal_11,throwOnChange,false);
    const currVal_12:any = 'true';
    this._NgModel_19_6.check_isDisabled(currVal_12,throwOnChange,false);
    const currVal_13:any = this.parent.context.project.isActive;
    this._NgModel_19_6.check_model(currVal_13,throwOnChange,false);
    this._NgModel_19_6.detectChangesInternal(this,this._el_19,throwOnChange);
    this._NgControlStatus_19_8.detectChangesInternal(this,this._el_19,throwOnChange);
    this._StyleCompatibility_19_9.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_21:any = this.parent.context.project.applicationUsers;
    this._NgFor_62_6.check_ngForOf(currVal_21,throwOnChange,false);
    this._NgFor_62_6.detectChangesInternal(this,this._anchor_62,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n\n            ',this.parent.context.project.name,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_6,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n\n            ',this.parent.context.project.slackChannelName,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_12,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_6:any = this._MdCheckbox_19_4.context.indeterminate;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_19,'md-checkbox-indeterminate',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._MdCheckbox_19_4.context.checked;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_19,'md-checkbox-checked',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._MdCheckbox_19_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_19,'md-checkbox-disabled',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = (this._MdCheckbox_19_4.context.align == 'end');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'md-checkbox-align-end',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._MdCheckbox_19_4.context.hasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_19,'md-checkbox-focused',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = this._NgControlStatus_19_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_19,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_19_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_19,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_19_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_19,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_19_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_19,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_19_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_19,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_19_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_19,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = import4.interpolate(2,'',this.parent.context.teamLeaderFirstName,'-',this.parent.context.teamLeaderEmail,'');
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setText(this._text_36,currVal_20);
      this._expr_20 = currVal_20;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_19_6.context.ngOnDestroy();
  }
  private _handle_ngModelChange_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.project.isActive = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ProjectViewComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent2,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'td',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.UniqueName,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProjectViewComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent2(viewUtils,parentInjector,declarationEl);
}