/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/users/user-edit/user-edit.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../app/users/user.service';
import * as import9 from '@angular/router/src/router_state';
import * as import10 from '@angular/router/src/router';
import * as import11 from 'md2/toast/toast';
import * as import12 from '../../../../app/login.service';
import * as import13 from '../../../../app/shared/loader.service';
import * as import14 from '../../../../app/shared/userrole.model';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '../../../node_modules/@angular2-material/button/button.ngfactory';
import * as import18 from '../../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import19 from '../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import20 from '../../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import21 from '../../../node_modules/@angular2-material/input/input.ngfactory';
import * as import22 from '../../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from '../../../node_modules/md2/core/compatibility/style-compatibility.ngfactory';
import * as import24 from '@angular/core/src/linker/query_list';
import * as import25 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import26 from '@angular/common/src/pipes/date_pipe';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from '@angular/core/src/linker/template_ref';
import * as import29 from '@angular/core/src/i18n/tokens';
import * as import30 from '@angular2-material/button/button';
import * as import31 from '@angular/forms/src/directives/validators';
import * as import32 from '@angular/forms/src/validators';
import * as import33 from '@angular2-material/input/input';
import * as import34 from '@angular/forms/src/directives/control_value_accessor';
import * as import35 from '@angular/forms/src/directives/ng_model';
import * as import36 from '@angular/forms/src/directives/ng_control';
import * as import37 from '@angular/forms/src/directives/ng_control_status';
import * as import38 from 'md2/core/compatibility/style-compatibility';
import * as import39 from '@angular/common/src/directives/ng_if';
import * as import40 from '@angular/forms/src/directives/ng_form';
import * as import41 from '@angular/forms/src/directives/control_container';
import * as import42 from '../../../node_modules/md2/select/select.ngfactory';
import * as import43 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import44 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import45 from '@angular/common/src/directives/ng_for';
import * as import46 from 'md2/select/select';
import * as import47 from '../../../node_modules/@angular2-material/checkbox/checkbox.ngfactory';
import * as import48 from '@angular2-material/checkbox/checkbox';
export class Wrapper_UserEditComponent {
  context:import0.UserEditComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.UserEditComponent(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_UserEditComponent_Host:import2.RenderComponentType = (null as any);
class _View_UserEditComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _UserEditComponent_0_4:Wrapper_UserEditComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent_Host0,renderType_UserEditComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserEditComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserEditComponent_0_4 = new Wrapper_UserEditComponent(this.parentInjector.get(import8.UserService),this.parentInjector.get(import9.ActivatedRoute),this.parentInjector.get(import10.Router),this.parentInjector.get(import11.Md2Toast),this.parentInjector.get(import12.LoginService),this.parentInjector.get(import13.LoaderService),this.parentInjector.get(import14.UserRole));
    this._appEl_0.initComponent(this._UserEditComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._UserEditComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.UserEditComponent) && (0 === requestNodeIndex))) { return this._UserEditComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._UserEditComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserEditComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_UserEditComponent_Host === (null as any))) { (renderType_UserEditComponent_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_UserEditComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserEditComponentNgFactory:import16.ComponentFactory<import0.UserEditComponent> = new import16.ComponentFactory<import0.UserEditComponent>('ng-component',viewFactory_UserEditComponent_Host0,import0.UserEditComponent);
const styles_UserEditComponent:any[] = ([] as any[]);
var renderType_UserEditComponent:import2.RenderComponentType = (null as any);
class _View_UserEditComponent0 extends import1.AppView<import0.UserEditComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _MdButton_12_4:import17.Wrapper_MdButton;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _NgForm_20_3:import18.Wrapper_NgForm;
  _ControlContainer_20_4:any;
  _NgControlStatusGroup_20_5:import19.Wrapper_NgControlStatusGroup;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _RequiredValidator_26_4:import20.Wrapper_RequiredValidator;
  _MaxLengthValidator_26_5:import20.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_26_6:any[];
  _MdInput_26_7:import21.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_26_8:any[];
  _NgModel_26_9:import22.Wrapper_NgModel;
  _NgControl_26_10:any;
  _NgControlStatus_26_11:import19.Wrapper_NgControlStatus;
  _StyleCompatibility_26_12:import23.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_26_0:import24.QueryList<any>;
  _query_MdHint_26_1:import24.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _RequiredValidator_37_4:import20.Wrapper_RequiredValidator;
  _MaxLengthValidator_37_5:import20.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_37_6:any[];
  _MdInput_37_7:import21.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_37_8:any[];
  _NgModel_37_9:import22.Wrapper_NgModel;
  _NgControl_37_10:any;
  _NgControlStatus_37_11:import19.Wrapper_NgControlStatus;
  _StyleCompatibility_37_12:import23.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_37_0:import24.QueryList<any>;
  _query_MdHint_37_1:import24.QueryList<any>;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _RequiredValidator_46_4:import20.Wrapper_RequiredValidator;
  _MaxLengthValidator_46_5:import20.Wrapper_MaxLengthValidator;
  _NG_VALIDATORS_46_6:any[];
  _MdInput_46_7:import21.Wrapper_MdInput;
  _NG_VALUE_ACCESSOR_46_8:any[];
  _NgModel_46_9:import22.Wrapper_NgModel;
  _NgControl_46_10:any;
  _NgControlStatus_46_11:import19.Wrapper_NgControlStatus;
  _StyleCompatibility_46_12:import23.Wrapper_StyleCompatibility;
  _query_MdPlaceholder_46_0:import24.QueryList<any>;
  _query_MdHint_46_1:import24.QueryList<any>;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _anchor_52:any;
  /*private*/ _appEl_52:import3.AppElement;
  _TemplateRef_52_5:any;
  _NgIf_52_6:import25.Wrapper_NgIf;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _anchor_83:any;
  /*private*/ _appEl_83:import3.AppElement;
  _TemplateRef_83_5:any;
  _NgIf_83_6:import25.Wrapper_NgIf;
  _text_84:any;
  _anchor_85:any;
  /*private*/ _appEl_85:import3.AppElement;
  _TemplateRef_85_5:any;
  _NgIf_85_6:import25.Wrapper_NgIf;
  _text_86:any;
  _anchor_87:any;
  /*private*/ _appEl_87:import3.AppElement;
  _TemplateRef_87_5:any;
  _NgIf_87_6:import25.Wrapper_NgIf;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  /*private*/ _appEl_92:import3.AppElement;
  _MdButton_92_4:import17.Wrapper_MdButton;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _text_97:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_58:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_72:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  _pipe_date_0:import26.DatePipe;
  _pipe_date_0_0:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_88:any;
  /*private*/ _expr_89:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent0,renderType_UserEditComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','user-edit');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','card-title-block');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','title  items');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'User Edit',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','text-right items');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn-back btn-green');
    this.renderer.setElementAttribute(this._el_12,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_12,'type','submit');
    this._appEl_12 = new import3.AppElement(12,10,this,this._el_12);
    var compView_12:any = import17.viewFactory_MdButton0(this.viewUtils,this.injector(12),this._appEl_12);
    this._MdButton_12_4 = new import17.Wrapper_MdButton(new import27.ElementRef(this._el_12),this.renderer);
    this._appEl_12.initComponent(this._MdButton_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),' ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'i',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','material-icons');
    this._text_15 = this.renderer.createText(this._el_14,'arrow_back',(null as any));
    this._text_16 = this.renderer.createText((null as any),'Back',(null as any));
      compView_12.create(this._MdButton_12_4.context,[([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_20_3 = new import18.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_20_4 = this._NgForm_20_3.context;
    this._NgControlStatusGroup_20_5 = new import19.Wrapper_NgControlStatusGroup(this._ControlContainer_20_4);
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','form-group');
    this._text_23 = this.renderer.createText(this._el_22,'\n            ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','half-width');
    this._text_25 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','full-width');
    this.renderer.setElementAttribute(this._el_26,'maxlength','255');
    this.renderer.setElementAttribute(this._el_26,'name','FirstName');
    this.renderer.setElementAttribute(this._el_26,'placeholder','First Name');
    this.renderer.setElementAttribute(this._el_26,'required','');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._appEl_26 = new import3.AppElement(26,24,this,this._el_26);
    var compView_26:any = import21.viewFactory_MdInput0(this.viewUtils,this.injector(26),this._appEl_26);
    this._RequiredValidator_26_4 = new import20.Wrapper_RequiredValidator();
    this._MaxLengthValidator_26_5 = new import20.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_26_6 = [
      this._RequiredValidator_26_4.context,
      this._MaxLengthValidator_26_5.context
    ]
    ;
    this._MdInput_26_7 = new import21.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_26_8 = [this._MdInput_26_7.context];
    this._NgModel_26_9 = new import22.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_26_6,(null as any),this._NG_VALUE_ACCESSOR_26_8);
    this._NgControl_26_10 = this._NgModel_26_9.context;
    this._NgControlStatus_26_11 = new import19.Wrapper_NgControlStatus(this._NgControl_26_10);
    this._StyleCompatibility_26_12 = new import23.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_26));
    this._query_MdPlaceholder_26_0 = new import24.QueryList<any>();
    this._query_MdHint_26_1 = new import24.QueryList<any>();
    this._appEl_26.initComponent(this._MdInput_26_7.context,([] as any[]),compView_26);
    this._query_MdPlaceholder_26_0.reset(([] as any[]));
    this._MdInput_26_7.context._placeholderChild = this._query_MdPlaceholder_26_0.first;
    compView_26.create(this._MdInput_26_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','error');
    this._text_29 = this.renderer.createText(this._el_28,'First Name is required',(null as any));
    this._text_30 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','form-group');
    this._text_34 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','half-width');
    this._text_36 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','full-width');
    this.renderer.setElementAttribute(this._el_37,'maxlength','255');
    this.renderer.setElementAttribute(this._el_37,'name','LastName');
    this.renderer.setElementAttribute(this._el_37,'placeholder','Last Name');
    this.renderer.setElementAttribute(this._el_37,'required','');
    this.renderer.setElementAttribute(this._el_37,'type','text');
    this._appEl_37 = new import3.AppElement(37,35,this,this._el_37);
    var compView_37:any = import21.viewFactory_MdInput0(this.viewUtils,this.injector(37),this._appEl_37);
    this._RequiredValidator_37_4 = new import20.Wrapper_RequiredValidator();
    this._MaxLengthValidator_37_5 = new import20.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_37_6 = [
      this._RequiredValidator_37_4.context,
      this._MaxLengthValidator_37_5.context
    ]
    ;
    this._MdInput_37_7 = new import21.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_37_8 = [this._MdInput_37_7.context];
    this._NgModel_37_9 = new import22.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_37_6,(null as any),this._NG_VALUE_ACCESSOR_37_8);
    this._NgControl_37_10 = this._NgModel_37_9.context;
    this._NgControlStatus_37_11 = new import19.Wrapper_NgControlStatus(this._NgControl_37_10);
    this._StyleCompatibility_37_12 = new import23.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_37));
    this._query_MdPlaceholder_37_0 = new import24.QueryList<any>();
    this._query_MdHint_37_1 = new import24.QueryList<any>();
    this._appEl_37.initComponent(this._MdInput_37_7.context,([] as any[]),compView_37);
    this._query_MdPlaceholder_37_0.reset(([] as any[]));
    this._MdInput_37_7.context._placeholderChild = this._query_MdPlaceholder_37_0.first;
    compView_37.create(this._MdInput_37_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_35,'\n                ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','error');
    this._text_40 = this.renderer.createText(this._el_39,'Last Name is required',(null as any));
    this._text_41 = this.renderer.createText(this._el_35,'\n            ',(null as any));
    this._text_42 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._text_43 = this.renderer.createText(this._el_20,'\n       \n        ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','form-group');
    this._text_45 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'md-input',(null as any));
    this.renderer.setElementAttribute(this._el_46,'maxlength','255');
    this.renderer.setElementAttribute(this._el_46,'name','SlackUserName');
    this.renderer.setElementAttribute(this._el_46,'placeholder','Slack User Name');
    this.renderer.setElementAttribute(this._el_46,'required','');
    this.renderer.setElementAttribute(this._el_46,'type','text');
    this._appEl_46 = new import3.AppElement(46,44,this,this._el_46);
    var compView_46:any = import21.viewFactory_MdInput0(this.viewUtils,this.injector(46),this._appEl_46);
    this._RequiredValidator_46_4 = new import20.Wrapper_RequiredValidator();
    this._MaxLengthValidator_46_5 = new import20.Wrapper_MaxLengthValidator();
    this._NG_VALIDATORS_46_6 = [
      this._RequiredValidator_46_4.context,
      this._MaxLengthValidator_46_5.context
    ]
    ;
    this._MdInput_46_7 = new import21.Wrapper_MdInput();
    this._NG_VALUE_ACCESSOR_46_8 = [this._MdInput_46_7.context];
    this._NgModel_46_9 = new import22.Wrapper_NgModel(this._ControlContainer_20_4,this._NG_VALIDATORS_46_6,(null as any),this._NG_VALUE_ACCESSOR_46_8);
    this._NgControl_46_10 = this._NgModel_46_9.context;
    this._NgControlStatus_46_11 = new import19.Wrapper_NgControlStatus(this._NgControl_46_10);
    this._StyleCompatibility_46_12 = new import23.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_46));
    this._query_MdPlaceholder_46_0 = new import24.QueryList<any>();
    this._query_MdHint_46_1 = new import24.QueryList<any>();
    this._appEl_46.initComponent(this._MdInput_46_7.context,([] as any[]),compView_46);
    this._query_MdPlaceholder_46_0.reset(([] as any[]));
    this._MdInput_46_7.context._placeholderChild = this._query_MdPlaceholder_46_0.first;
    compView_46.create(this._MdInput_46_7.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_44,'\n            ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_44,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','error');
    this._text_49 = this.renderer.createText(this._el_48,'Slack User Name is required',(null as any));
    this._text_50 = this.renderer.createText(this._el_44,'\n        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_20,'\n\n        ',(null as any));
    this._anchor_52 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_52 = new import3.AppElement(52,20,this,this._anchor_52);
    this._TemplateRef_52_5 = new import28.TemplateRef_(this._appEl_52,viewFactory_UserEditComponent1);
    this._NgIf_52_6 = new import25.Wrapper_NgIf(this._appEl_52.vcRef,this._TemplateRef_52_5);
    this._text_53 = this.renderer.createText(this._el_20,'\n\n     \n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','form-group');
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'label',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','lb-label');
    this._text_57 = this.renderer.createText(this._el_56,'Email:',(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'',(null as any));
    this._text_59 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','form-group');
    this._text_61 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'label',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','lb-label');
    this._text_63 = this.renderer.createText(this._el_62,'Casual Leave:',(null as any));
    this._text_64 = this.renderer.createText(this._el_60,'',(null as any));
    this._text_65 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','form-group');
    this._text_67 = this.renderer.createText(this._el_66,'\n            ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'label',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','lb-label');
    this._text_69 = this.renderer.createText(this._el_68,'Sick Leave:',(null as any));
    this._text_70 = this.renderer.createText(this._el_66,'',(null as any));
    this._text_71 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_72,'class','form-group');
    this._text_73 = this.renderer.createText(this._el_72,'\n            ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_72,'label',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','lb-label');
    this._text_75 = this.renderer.createText(this._el_74,'Date of Joining:',(null as any));
    this._text_76 = this.renderer.createText(this._el_72,'',(null as any));
    this._text_77 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_78,'class','form-group');
    this._text_79 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_78,'label',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','lb-label');
    this._text_81 = this.renderer.createText(this._el_80,'Status:',(null as any));
    this._text_82 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._anchor_83 = this.renderer.createTemplateAnchor(this._el_78,(null as any));
    this._appEl_83 = new import3.AppElement(83,78,this,this._anchor_83);
    this._TemplateRef_83_5 = new import28.TemplateRef_(this._appEl_83,viewFactory_UserEditComponent3);
    this._NgIf_83_6 = new import25.Wrapper_NgIf(this._appEl_83.vcRef,this._TemplateRef_83_5);
    this._text_84 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._anchor_85 = this.renderer.createTemplateAnchor(this._el_78,(null as any));
    this._appEl_85 = new import3.AppElement(85,78,this,this._anchor_85);
    this._TemplateRef_85_5 = new import28.TemplateRef_(this._appEl_85,viewFactory_UserEditComponent4);
    this._NgIf_85_6 = new import25.Wrapper_NgIf(this._appEl_85.vcRef,this._TemplateRef_85_5);
    this._text_86 = this.renderer.createText(this._el_78,'\n            ',(null as any));
    this._anchor_87 = this.renderer.createTemplateAnchor(this._el_78,(null as any));
    this._appEl_87 = new import3.AppElement(87,78,this,this._anchor_87);
    this._TemplateRef_87_5 = new import28.TemplateRef_(this._appEl_87,viewFactory_UserEditComponent5);
    this._NgIf_87_6 = new import25.Wrapper_NgIf(this._appEl_87.vcRef,this._TemplateRef_87_5);
    this._text_88 = this.renderer.createText(this._el_78,'\n        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_20,'div',(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'\n            ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'button',(null as any));
    this.renderer.setElementAttribute(this._el_92,'class','btn-green');
    this.renderer.setElementAttribute(this._el_92,'md-raised-button','');
    this.renderer.setElementAttribute(this._el_92,'type','submit');
    this._appEl_92 = new import3.AppElement(92,90,this,this._el_92);
    var compView_92:any = import17.viewFactory_MdButton0(this.viewUtils,this.injector(92),this._appEl_92);
    this._MdButton_92_4 = new import17.Wrapper_MdButton(new import27.ElementRef(this._el_92),this.renderer);
    this._appEl_92.initComponent(this._MdButton_92_4.context,([] as any[]),compView_92);
    this._text_93 = this.renderer.createText((null as any),'Update',(null as any));
    compView_92.create(this._MdButton_92_4.context,[([] as any[]).concat([this._text_93])],(null as any));
    this._text_94 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._text_95 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_96 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_97 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_12,'mousedown',this.eventHandler(this._handle_mousedown_12_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_12,'focus',this.eventHandler(this._handle_focus_12_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_12,'blur',this.eventHandler(this._handle_blur_12_3.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_20,'submit',this.eventHandler(this._handle_submit_20_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_20,'reset',this.eventHandler(this._handle_reset_20_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_26,'click',this.eventHandler(this._handle_click_26_1.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_26_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_37,'ngModelChange',this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_1.bind(this)));
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_37_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_37_0.bind(this)));
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    var disposable_10:Function = this.renderer.listen(this._el_46,'ngModelChange',this.eventHandler(this._handle_ngModelChange_46_0.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_46,'click',this.eventHandler(this._handle_click_46_1.bind(this)));
    this._expr_58 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_46_9.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_46_0.bind(this)));
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    this._expr_71 = import7.UNINITIALIZED;
    this._expr_72 = import7.UNINITIALIZED;
    this._expr_73 = import7.UNINITIALIZED;
    this._expr_74 = import7.UNINITIALIZED;
    this._expr_75 = import7.UNINITIALIZED;
    this._expr_77 = import7.UNINITIALIZED;
    this._expr_78 = import7.UNINITIALIZED;
    this._expr_79 = import7.UNINITIALIZED;
    this._pipe_date_0 = new import26.DatePipe(this.parentInjector.get(import29.LOCALE_ID));
    this._pipe_date_0_0 = import4.pureProxy2(this._pipe_date_0.transform.bind(this._pipe_date_0));
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_88 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_92,'click',this.eventHandler(this._handle_click_92_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_92,'mousedown',this.eventHandler(this._handle_mousedown_92_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_92,'focus',this.eventHandler(this._handle_focus_92_2.bind(this)));
    var disposable_15:Function = this.renderer.listen(this._el_92,'blur',this.eventHandler(this._handle_blur_92_3.bind(this)));
    this._expr_89 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._anchor_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._anchor_83,
      this._text_84,
      this._anchor_85,
      this._text_86,
      this._anchor_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._text_97
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import30.MdButton) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_12_4.context; }
    if (((token === import31.RequiredValidator) && (26 === requestNodeIndex))) { return this._RequiredValidator_26_4.context; }
    if (((token === import31.MaxLengthValidator) && (26 === requestNodeIndex))) { return this._MaxLengthValidator_26_5.context; }
    if (((token === import32.NG_VALIDATORS) && (26 === requestNodeIndex))) { return this._NG_VALIDATORS_26_6; }
    if (((token === import33.MdInput) && (26 === requestNodeIndex))) { return this._MdInput_26_7.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (26 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_26_8; }
    if (((token === import35.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_9.context; }
    if (((token === import36.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_10; }
    if (((token === import37.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_11.context; }
    if (((token === import38.StyleCompatibility) && (26 === requestNodeIndex))) { return this._StyleCompatibility_26_12.context; }
    if (((token === import31.RequiredValidator) && (37 === requestNodeIndex))) { return this._RequiredValidator_37_4.context; }
    if (((token === import31.MaxLengthValidator) && (37 === requestNodeIndex))) { return this._MaxLengthValidator_37_5.context; }
    if (((token === import32.NG_VALIDATORS) && (37 === requestNodeIndex))) { return this._NG_VALIDATORS_37_6; }
    if (((token === import33.MdInput) && (37 === requestNodeIndex))) { return this._MdInput_37_7.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (37 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_37_8; }
    if (((token === import35.NgModel) && (37 === requestNodeIndex))) { return this._NgModel_37_9.context; }
    if (((token === import36.NgControl) && (37 === requestNodeIndex))) { return this._NgControl_37_10; }
    if (((token === import37.NgControlStatus) && (37 === requestNodeIndex))) { return this._NgControlStatus_37_11.context; }
    if (((token === import38.StyleCompatibility) && (37 === requestNodeIndex))) { return this._StyleCompatibility_37_12.context; }
    if (((token === import31.RequiredValidator) && (46 === requestNodeIndex))) { return this._RequiredValidator_46_4.context; }
    if (((token === import31.MaxLengthValidator) && (46 === requestNodeIndex))) { return this._MaxLengthValidator_46_5.context; }
    if (((token === import32.NG_VALIDATORS) && (46 === requestNodeIndex))) { return this._NG_VALIDATORS_46_6; }
    if (((token === import33.MdInput) && (46 === requestNodeIndex))) { return this._MdInput_46_7.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (46 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_46_8; }
    if (((token === import35.NgModel) && (46 === requestNodeIndex))) { return this._NgModel_46_9.context; }
    if (((token === import36.NgControl) && (46 === requestNodeIndex))) { return this._NgControl_46_10; }
    if (((token === import37.NgControlStatus) && (46 === requestNodeIndex))) { return this._NgControlStatus_46_11.context; }
    if (((token === import38.StyleCompatibility) && (46 === requestNodeIndex))) { return this._StyleCompatibility_46_12.context; }
    if (((token === import28.TemplateRef) && (52 === requestNodeIndex))) { return this._TemplateRef_52_5; }
    if (((token === import39.NgIf) && (52 === requestNodeIndex))) { return this._NgIf_52_6.context; }
    if (((token === import28.TemplateRef) && (83 === requestNodeIndex))) { return this._TemplateRef_83_5; }
    if (((token === import39.NgIf) && (83 === requestNodeIndex))) { return this._NgIf_83_6.context; }
    if (((token === import28.TemplateRef) && (85 === requestNodeIndex))) { return this._TemplateRef_85_5; }
    if (((token === import39.NgIf) && (85 === requestNodeIndex))) { return this._NgIf_85_6.context; }
    if (((token === import28.TemplateRef) && (87 === requestNodeIndex))) { return this._TemplateRef_87_5; }
    if (((token === import39.NgIf) && (87 === requestNodeIndex))) { return this._NgIf_87_6.context; }
    if (((token === import30.MdButton) && ((92 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._MdButton_92_4.context; }
    if (((token === import40.NgForm) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 95)))) { return this._NgForm_20_3.context; }
    if (((token === import41.ControlContainer) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 95)))) { return this._ControlContainer_20_4; }
    if (((token === import37.NgControlStatusGroup) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 95)))) { return this._NgControlStatusGroup_20_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    if (this._MdButton_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._NgForm_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._NgControlStatusGroup_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_15:any = '';
    this._RequiredValidator_26_4.check_required(currVal_15,throwOnChange,false);
    this._RequiredValidator_26_4.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_17:any = '255';
    this._MaxLengthValidator_26_5.check_maxlength(currVal_17,throwOnChange,false);
    this._MaxLengthValidator_26_5.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_19:any = '255';
    this._MdInput_26_7.check_maxlength(currVal_19,throwOnChange,false);
    const currVal_20:any = 'First Name';
    this._MdInput_26_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = '';
    this._MdInput_26_7.check_required(currVal_21,throwOnChange,false);
    const currVal_22:any = 'text';
    this._MdInput_26_7.check_type(currVal_22,throwOnChange,false);
    const currVal_23:any = 'FirstName';
    this._MdInput_26_7.check_name(currVal_23,throwOnChange,false);
    this._MdInput_26_7.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_25:any = 'FirstName';
    this._NgModel_26_9.check_name(currVal_25,throwOnChange,false);
    const currVal_26:any = this.context.user.FirstName;
    this._NgModel_26_9.check_model(currVal_26,throwOnChange,false);
    this._NgModel_26_9.detectChangesInternal(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_11.detectChangesInternal(this,this._el_26,throwOnChange);
    this._StyleCompatibility_26_12.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_36:any = '';
    this._RequiredValidator_37_4.check_required(currVal_36,throwOnChange,false);
    this._RequiredValidator_37_4.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_38:any = '255';
    this._MaxLengthValidator_37_5.check_maxlength(currVal_38,throwOnChange,false);
    this._MaxLengthValidator_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_40:any = '255';
    this._MdInput_37_7.check_maxlength(currVal_40,throwOnChange,false);
    const currVal_41:any = 'Last Name';
    this._MdInput_37_7.check_placeholder(currVal_41,throwOnChange,false);
    const currVal_42:any = '';
    this._MdInput_37_7.check_required(currVal_42,throwOnChange,false);
    const currVal_43:any = 'text';
    this._MdInput_37_7.check_type(currVal_43,throwOnChange,false);
    const currVal_44:any = 'LastName';
    this._MdInput_37_7.check_name(currVal_44,throwOnChange,false);
    this._MdInput_37_7.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_46:any = 'LastName';
    this._NgModel_37_9.check_name(currVal_46,throwOnChange,false);
    const currVal_47:any = this.context.user.LastName;
    this._NgModel_37_9.check_model(currVal_47,throwOnChange,false);
    this._NgModel_37_9.detectChangesInternal(this,this._el_37,throwOnChange);
    this._NgControlStatus_37_11.detectChangesInternal(this,this._el_37,throwOnChange);
    this._StyleCompatibility_37_12.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_57:any = '';
    this._RequiredValidator_46_4.check_required(currVal_57,throwOnChange,false);
    this._RequiredValidator_46_4.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_59:any = '255';
    this._MaxLengthValidator_46_5.check_maxlength(currVal_59,throwOnChange,false);
    this._MaxLengthValidator_46_5.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_61:any = '255';
    this._MdInput_46_7.check_maxlength(currVal_61,throwOnChange,false);
    const currVal_62:any = 'Slack User Name';
    this._MdInput_46_7.check_placeholder(currVal_62,throwOnChange,false);
    const currVal_63:any = '';
    this._MdInput_46_7.check_required(currVal_63,throwOnChange,false);
    const currVal_64:any = 'text';
    this._MdInput_46_7.check_type(currVal_64,throwOnChange,false);
    const currVal_65:any = 'SlackUserName';
    this._MdInput_46_7.check_name(currVal_65,throwOnChange,false);
    this._MdInput_46_7.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_67:any = 'SlackUserName';
    this._NgModel_46_9.check_name(currVal_67,throwOnChange,false);
    const currVal_68:any = this.context.user.SlackUserName;
    this._NgModel_46_9.check_model(currVal_68,throwOnChange,false);
    this._NgModel_46_9.detectChangesInternal(this,this._el_46,throwOnChange);
    this._NgControlStatus_46_11.detectChangesInternal(this,this._el_46,throwOnChange);
    this._StyleCompatibility_46_12.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_76:any = (this.context.admin == true);
    this._NgIf_52_6.check_ngIf(currVal_76,throwOnChange,false);
    this._NgIf_52_6.detectChangesInternal(this,this._anchor_52,throwOnChange);
    const currVal_81:any = (this.context.user.IsActive && (this.context.admin != true));
    this._NgIf_83_6.check_ngIf(currVal_81,throwOnChange,false);
    this._NgIf_83_6.detectChangesInternal(this,this._anchor_83,throwOnChange);
    const currVal_82:boolean = (!this.context.user.IsActive && (this.context.admin != true));
    this._NgIf_85_6.check_ngIf(currVal_82,throwOnChange,false);
    this._NgIf_85_6.detectChangesInternal(this,this._anchor_85,throwOnChange);
    const currVal_83:any = (this.context.admin == true);
    this._NgIf_87_6.check_ngIf(currVal_83,throwOnChange,false);
    this._NgIf_87_6.detectChangesInternal(this,this._anchor_87,throwOnChange);
    if (this._MdButton_92_4.detectChangesInternal(this,this._el_92,throwOnChange)) { this._appEl_92.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdHint_26_1.dirty) {
        this._query_MdHint_26_1.reset(([] as any[]));
        this._MdInput_26_7.context._hintChildren = this._query_MdHint_26_1;
        this._query_MdHint_26_1.notifyOnChanges();
      }
      if (this._query_MdHint_37_1.dirty) {
        this._query_MdHint_37_1.reset(([] as any[]));
        this._MdInput_37_7.context._hintChildren = this._query_MdHint_37_1;
        this._query_MdHint_37_1.notifyOnChanges();
      }
      if (this._query_MdHint_46_1.dirty) {
        this._query_MdHint_46_1.reset(([] as any[]));
        this._MdInput_46_7.context._hintChildren = this._query_MdHint_46_1;
        this._query_MdHint_46_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdInput_26_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_37_7.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdInput_46_7.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._MdButton_12_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_12,'md-button-focus',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatusGroup_20_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_20_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_20_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_20_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_20_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_20_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = (this._RequiredValidator_26_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementAttribute(this._el_26,'required',((currVal_16 == (null as any))? (null as any): currVal_16.toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = (this._MaxLengthValidator_26_5.context.maxlength? this._MaxLengthValidator_26_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_26,'maxlength',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_24:any = this._MdInput_26_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementAttribute(this._el_26,'align',((currVal_24 == (null as any))? (null as any): currVal_24.toString()));
      this._expr_24 = currVal_24;
    }
    const currVal_27:any = this._NgControlStatus_26_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_26_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_26_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_26_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_26_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_26_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:boolean = !((this._NgModel_26_9.context.touched && !this._NgModel_26_9.context.valid) && this._NgModel_26_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementProperty(this._el_28,'hidden',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_37:any = (this._RequiredValidator_37_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementAttribute(this._el_37,'required',((currVal_37 == (null as any))? (null as any): currVal_37.toString()));
      this._expr_37 = currVal_37;
    }
    const currVal_39:any = (this._MaxLengthValidator_37_5.context.maxlength? this._MaxLengthValidator_37_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementAttribute(this._el_37,'maxlength',((currVal_39 == (null as any))? (null as any): currVal_39.toString()));
      this._expr_39 = currVal_39;
    }
    const currVal_45:any = this._MdInput_37_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementAttribute(this._el_37,'align',((currVal_45 == (null as any))? (null as any): currVal_45.toString()));
      this._expr_45 = currVal_45;
    }
    const currVal_48:any = this._NgControlStatus_37_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_37,'ng-untouched',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_37_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_37,'ng-touched',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_37_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_37,'ng-pristine',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_37_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_37,'ng-dirty',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_37_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_37,'ng-valid',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_37_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_37,'ng-invalid',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:boolean = !((this._NgModel_37_9.context.touched && !this._NgModel_37_9.context.valid) && this._NgModel_37_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementProperty(this._el_39,'hidden',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_58:any = (this._RequiredValidator_46_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_58,currVal_58)) {
      this.renderer.setElementAttribute(this._el_46,'required',((currVal_58 == (null as any))? (null as any): currVal_58.toString()));
      this._expr_58 = currVal_58;
    }
    const currVal_60:any = (this._MaxLengthValidator_46_5.context.maxlength? this._MaxLengthValidator_46_5.context.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementAttribute(this._el_46,'maxlength',((currVal_60 == (null as any))? (null as any): currVal_60.toString()));
      this._expr_60 = currVal_60;
    }
    const currVal_66:any = this._MdInput_46_7.context._align;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementAttribute(this._el_46,'align',((currVal_66 == (null as any))? (null as any): currVal_66.toString()));
      this._expr_66 = currVal_66;
    }
    const currVal_69:any = this._NgControlStatus_46_11.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_46,'ng-untouched',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = this._NgControlStatus_46_11.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_46,'ng-touched',currVal_70);
      this._expr_70 = currVal_70;
    }
    const currVal_71:any = this._NgControlStatus_46_11.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementClass(this._el_46,'ng-pristine',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_72:any = this._NgControlStatus_46_11.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_72,currVal_72)) {
      this.renderer.setElementClass(this._el_46,'ng-dirty',currVal_72);
      this._expr_72 = currVal_72;
    }
    const currVal_73:any = this._NgControlStatus_46_11.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setElementClass(this._el_46,'ng-valid',currVal_73);
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = this._NgControlStatus_46_11.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setElementClass(this._el_46,'ng-invalid',currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:boolean = !((this._NgModel_46_9.context.touched && !this._NgModel_46_9.context.valid) && this._NgModel_46_9.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setElementProperty(this._el_48,'hidden',currVal_75);
      this._expr_75 = currVal_75;
    }
    const currVal_77:any = import4.interpolate(1,'\n            ',this.context.user.Email,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this.renderer.setText(this._text_58,currVal_77);
      this._expr_77 = currVal_77;
    }
    const currVal_78:any = import4.interpolate(1,'\n            ',this.context.user.NumberOfCasualLeave,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setText(this._text_64,currVal_78);
      this._expr_78 = currVal_78;
    }
    const currVal_79:any = import4.interpolate(1,'\n            ',this.context.user.NumberOfSickLeave,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setText(this._text_70,currVal_79);
      this._expr_79 = currVal_79;
    }
    valUnwrapper.reset();
    const currVal_80:any = import4.interpolate(1,'\n            ',valUnwrapper.unwrap(import4.castByValue(this._pipe_date_0_0,this._pipe_date_0.transform)(this.context.user.JoiningDate,'dd/MM/yyyy')),'\n        ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_80,currVal_80))) {
      this.renderer.setText(this._text_76,currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_88:boolean = !this._NgForm_20_3.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_88,currVal_88)) {
      this.renderer.setElementProperty(this._el_92,'disabled',currVal_88);
      this._expr_88 = currVal_88;
    }
    const currVal_89:any = this._MdButton_92_4.context._isKeyboardFocused;
    if (import4.checkBinding(throwOnChange,this._expr_89,currVal_89)) {
      this.renderer.setElementClass(this._el_92,'md-button-focus',currVal_89);
      this._expr_89 = currVal_89;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_26_9.context.ngOnDestroy();
    this._NgModel_37_9.context.ngOnDestroy();
    this._NgModel_46_9.context.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goBack()) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_12_1($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_12_2($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_12_3($event:any):boolean {
    this._appEl_12.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_12_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_20_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_20_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.FirstName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_26_1($event:any):boolean {
    this._appEl_26.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_26_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.LastName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_1($event:any):boolean {
    this._appEl_37.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_37_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_46_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.SlackUserName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_46_1($event:any):boolean {
    this._appEl_46.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdInput_46_7.context.focus()) !== false);
    return (true && pd_0);
  }
  private _handle_click_92_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.editUser(this.context.user)) !== false);
    return (true && pd_0);
  }
  private _handle_mousedown_92_1($event:any):boolean {
    this._appEl_92.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_92_4.context._setMousedown()) !== false);
    return (true && pd_0);
  }
  private _handle_focus_92_2($event:any):boolean {
    this._appEl_92.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_92_4.context._setKeyboardFocus()) !== false);
    return (true && pd_0);
  }
  private _handle_blur_92_3($event:any):boolean {
    this._appEl_92.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MdButton_92_4.context._removeKeyboardFocus()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UserEditComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.UserEditComponent> {
  if ((renderType_UserEditComponent === (null as any))) { (renderType_UserEditComponent = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_UserEditComponent,{})); }
  return new _View_UserEditComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserEditComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _RequiredValidator_4_4:import20.Wrapper_RequiredValidator;
  _NG_VALIDATORS_4_5:any[];
  _NgModel_4_6:import22.Wrapper_NgModel;
  _NgControl_4_7:any;
  _NgControlStatus_4_8:import19.Wrapper_NgControlStatus;
  _Md2Select_4_9:import42.Wrapper_Md2Select;
  _query_Md2Option_4_0:import24.QueryList<any>;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _TemplateRef_6_5:any;
  _NgFor_6_6:import43.Wrapper_NgFor;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent1,renderType_UserEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','form-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','half-width');
    this.renderer.setElementAttribute(this._el_2,'style','position:relative');
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'md2-select',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','field');
    this.renderer.setElementAttribute(this._el_4,'name','UserRole');
    this.renderer.setElementAttribute(this._el_4,'placeholder','User Role');
    this.renderer.setElementAttribute(this._el_4,'required','');
    this.renderer.setElementAttribute(this._el_4,'role','select');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import42.viewFactory_Md2Select0(this.viewUtils,this.injector(4),this._appEl_4);
    this._RequiredValidator_4_4 = new import20.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_4_5 = [this._RequiredValidator_4_4.context];
    this._NgModel_4_6 = new import22.Wrapper_NgModel((<_View_UserEditComponent0>this.parent)._ControlContainer_20_4,this._NG_VALIDATORS_4_5,(null as any),(null as any));
    this._NgControl_4_7 = this._NgModel_4_6.context;
    this._NgControlStatus_4_8 = new import19.Wrapper_NgControlStatus(this._NgControl_4_7);
    this._Md2Select_4_9 = new import42.Wrapper_Md2Select(new import27.ElementRef(this._el_4),this._NgControl_4_7);
    this._query_Md2Option_4_0 = new import24.QueryList<any>();
    this._appEl_4.initComponent(this._Md2Select_4_9.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_6 = new import3.AppElement(6,4,this,this._anchor_6);
    this._TemplateRef_6_5 = new import28.TemplateRef_(this._appEl_6,viewFactory_UserEditComponent2);
    this._NgFor_6_6 = new import43.Wrapper_NgFor(this._appEl_6.vcRef,this._TemplateRef_6_5,this.parent.parentInjector.get(import44.IterableDiffers),this.parent.ref);
    this._text_7 = this.renderer.createText((null as any),'\n                ',(null as any));
      compView_4.create(this._Md2Select_4_9.context,[([] as any[]).concat([
        this._text_5,
        this._appEl_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','error');
    this._text_11 = this.renderer.createText(this._el_10,'Please Select User Role',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'ngModelChange',this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_4,'keydown',this.eventHandler(this._handle_keydown_4_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_4,'blur',this.eventHandler(this._handle_blur_4_3.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_4_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import45.NgFor) && (6 === requestNodeIndex))) { return this._NgFor_6_6.context; }
    if (((token === import31.RequiredValidator) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RequiredValidator_4_4.context; }
    if (((token === import32.NG_VALIDATORS) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NG_VALIDATORS_4_5; }
    if (((token === import35.NgModel) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgModel_4_6.context; }
    if (((token === import36.NgControl) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgControl_4_7; }
    if (((token === import37.NgControlStatus) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._NgControlStatus_4_8.context; }
    if (((token === import46.Md2Select) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Md2Select_4_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = '';
    this._RequiredValidator_4_4.check_required(currVal_4,throwOnChange,false);
    this._RequiredValidator_4_4.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_6:any = 'UserRole';
    this._NgModel_4_6.check_name(currVal_6,throwOnChange,false);
    const currVal_7:any = this.parent.context.user.RoleName;
    this._NgModel_4_6.check_model(currVal_7,throwOnChange,false);
    this._NgModel_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    this._NgControlStatus_4_8.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_14:any = 'UserRole';
    this._Md2Select_4_9.check_name(currVal_14,throwOnChange,false);
    const currVal_15:any = 'User Role';
    this._Md2Select_4_9.check_placeholder(currVal_15,throwOnChange,false);
    const currVal_16:any = '';
    this._Md2Select_4_9.check_required(currVal_16,throwOnChange,false);
    this._Md2Select_4_9.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_23:any = this.parent.context.listOfRoles;
    this._NgFor_6_6.check_ngForOf(currVal_23,throwOnChange,false);
    this._NgFor_6_6.detectChangesInternal(this,this._anchor_6,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Md2Option_4_0.dirty) {
          this._query_Md2Option_4_0.reset([this._appEl_6.mapNestedViews(_View_UserEditComponent2,(nestedView:_View_UserEditComponent2):any => {
            return [nestedView._Md2Option_0_4.context];
        })]);
        this._Md2Select_4_9.context.options = this._query_Md2Option_4_0;
        this._query_Md2Option_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Md2Select_4_9.context.ngAfterContentInit(); }
      this._Md2Select_4_9.context.ngAfterContentChecked();
    }
    const currVal_5:any = (this._RequiredValidator_4_4.context.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementAttribute(this._el_4,'required',((currVal_5 == (null as any))? (null as any): currVal_5.toString()));
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._NgControlStatus_4_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_4,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_4_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_4,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_4_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_4,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_4_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_4,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_4_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_4,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_4_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_4,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_17:any = (this._Md2Select_4_9.context.disabled? (0 - 1): this._Md2Select_4_9.context.tabindex);
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementProperty(this._el_4,'tabIndex',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._Md2Select_4_9.context.placeholder;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementAttribute(this._el_4,'aria-label',((currVal_18 == (null as any))? (null as any): currVal_18.toString()));
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._Md2Select_4_9.context.required.toString();
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementAttribute(this._el_4,'aria-required',((currVal_19 == (null as any))? (null as any): currVal_19.toString()));
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._Md2Select_4_9.context.disabled.toString();
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementAttribute(this._el_4,'aria-disabled',((currVal_20 == (null as any))? (null as any): currVal_20.toString()));
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = (((this._Md2Select_4_9.context._control == (null as any))? (null as any): this._Md2Select_4_9.context._control.invalid) || 'false');
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementAttribute(this._el_4,'aria-invalid',((currVal_21 == (null as any))? (null as any): currVal_21.toString()));
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._Md2Select_4_9.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_4,'md2-select-disabled',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:boolean = !((this._NgModel_4_6.context.touched && !this._NgModel_4_6.context.valid) && this._NgModel_4_6.context.errors.required);
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementProperty(this._el_10,'hidden',currVal_24);
      this._expr_24 = currVal_24;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_4_6.context.ngOnDestroy();
  }
  private _handle_ngModelChange_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.user.RoleName = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_4_1($event:any):boolean {
    this._appEl_4.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Select_4_9.context.onClick($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keydown_4_2($event:any):boolean {
    this._appEl_4.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Select_4_9.context._handleKeydown($event)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_4_3($event:any):boolean {
    this._appEl_4.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Select_4_9.context._onBlur()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserEditComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserEditComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_UserEditComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Md2Option_0_4:import42.Wrapper_Md2Option;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent2,renderType_UserEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'md2-option',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','option');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import42.viewFactory_Md2Option0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Md2Option_0_4 = new import42.Wrapper_Md2Option((<_View_UserEditComponent1>this.parent)._Md2Select_4_9.context,this.parent.parent.parentInjector.get(import46.Md2SelectDispatcher),new import27.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._Md2Option_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    compView_0.create(this._Md2Option_0_4.context,[([] as any[]).concat([this._text_1])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Md2Option) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Md2Option_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.$implicit.name;
    this._Md2Option_0_4.check_value(currVal_1,throwOnChange,false);
    this._Md2Option_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._Md2Option_0_4.context.focused;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'md2-option-focused',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Md2Option_0_4.context.id;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._Md2Option_0_4.context.selected;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'md2-option-selected',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._Md2Option_0_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'md2-option-disabled',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_1,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { this._Md2Option_0_4.context.ngAfterViewChecked(); }
  }
  dirtyParentQueriesInternal():void {
    (<_View_UserEditComponent1>this.parent)._query_Md2Option_4_0.setDirty();
  }
  private _handle_click_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Md2Option_0_4.context.onOptionClick($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserEditComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserEditComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_UserEditComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent3,renderType_UserEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'label',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Active',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_UserEditComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserEditComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_UserEditComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent4,renderType_UserEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'label',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Inactive',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_UserEditComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserEditComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_UserEditComponent5 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MdCheckbox_0_4:import47.Wrapper_MdCheckbox;
  _NG_VALUE_ACCESSOR_0_5:any[];
  _NgModel_0_6:import22.Wrapper_NgModel;
  _NgControl_0_7:any;
  _NgControlStatus_0_8:import19.Wrapper_NgControlStatus;
  _StyleCompatibility_0_9:import23.Wrapper_StyleCompatibility;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_UserEditComponent5,renderType_UserEditComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'md-checkbox',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','chckbox');
    this.renderer.setElementAttribute(this._el_0,'name','IsActive');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import47.viewFactory_MdCheckbox0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MdCheckbox_0_4 = new import47.Wrapper_MdCheckbox(this.renderer,new import27.ElementRef(this._el_0));
    this._NG_VALUE_ACCESSOR_0_5 = [this._MdCheckbox_0_4.context];
    this._NgModel_0_6 = new import22.Wrapper_NgModel((<_View_UserEditComponent0>this.parent)._ControlContainer_20_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_0_5);
    this._NgControl_0_7 = this._NgModel_0_6.context;
    this._NgControlStatus_0_8 = new import19.Wrapper_NgControlStatus(this._NgControl_0_7);
    this._StyleCompatibility_0_9 = new import23.Wrapper_StyleCompatibility(this.renderer,new import27.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._MdCheckbox_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MdCheckbox_0_4.context,[([] as any[])],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngModelChange',this.eventHandler(this._handle_ngModelChange_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_0_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_0_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.MdCheckbox) && (0 === requestNodeIndex))) { return this._MdCheckbox_0_4.context; }
    if (((token === import34.NG_VALUE_ACCESSOR) && (0 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_0_5; }
    if (((token === import35.NgModel) && (0 === requestNodeIndex))) { return this._NgModel_0_6.context; }
    if (((token === import36.NgControl) && (0 === requestNodeIndex))) { return this._NgControl_0_7; }
    if (((token === import37.NgControlStatus) && (0 === requestNodeIndex))) { return this._NgControlStatus_0_8.context; }
    if (((token === import38.StyleCompatibility) && (0 === requestNodeIndex))) { return this._StyleCompatibility_0_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'chckbox';
    this._MdCheckbox_0_4.check_id(currVal_1,throwOnChange,false);
    const currVal_2:any = 'IsActive';
    this._MdCheckbox_0_4.check_name(currVal_2,throwOnChange,false);
    if (this._MdCheckbox_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'IsActive';
    this._NgModel_0_6.check_name(currVal_8,throwOnChange,false);
    const currVal_9:any = this.parent.context.user.IsActive;
    this._NgModel_0_6.check_model(currVal_9,throwOnChange,false);
    this._NgModel_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    this._NgControlStatus_0_8.detectChangesInternal(this,this._el_0,throwOnChange);
    this._StyleCompatibility_0_9.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._MdCheckbox_0_4.context.indeterminate;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'md-checkbox-indeterminate',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._MdCheckbox_0_4.context.checked;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'md-checkbox-checked',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._MdCheckbox_0_4.context.disabled;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'md-checkbox-disabled',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = (this._MdCheckbox_0_4.context.align == 'end');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'md-checkbox-align-end',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._MdCheckbox_0_4.context.hasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'md-checkbox-focused',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._NgControlStatus_0_8.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_0_8.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_0_8.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_0_8.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_0_8.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_0_8.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_0_6.context.ngOnDestroy();
  }
  private _handle_ngModelChange_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.user.IsActive = $event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UserEditComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_UserEditComponent5(viewUtils,parentInjector,declarationEl);
}